export default function (hand) {
  var ao1_85 = [
    {
      bidder: "o1",
      weight: 1,
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: 8,
      maxNumC: 8,
      o1Index: 21,
      o1Bid: "5c",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: 8,
      o1Index: 21,
      o1Bid: "5c",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: 8,
      o1Index: 21,
      o1Bid: "5c",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: 8,
      maxNumC: 8,
      o1Index: 21,
      o1Bid: "5c",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: 8,
      o1Index: 21,
      o1Bid: "5c",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: 8,
      o1Index: 21,
      o1Bid: "5c",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: 8,
      maxNumC: 8,
      o1Index: 21,
      o1Bid: "5c",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: 8,
      o1Index: 21,
      o1Bid: "5c",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: 8,
      o1Index: 21,
      o1Bid: "5c",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: 8,
      minNumC: 5,
      maxNumC: 5,
      o1Index: 22,
      o1Bid: "5d",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: 8,
      maxNumD: 8,
      minNumC: "",
      maxNumC: "",
      o1Index: 22,
      o1Bid: "5d",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: 8,
      minNumC: "",
      maxNumC: "",
      o1Index: 22,
      o1Bid: "5d",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: 8,
      minNumC: 5,
      maxNumC: 5,
      o1Index: 22,
      o1Bid: "5d",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: 8,
      maxNumD: 8,
      minNumC: "",
      maxNumC: "",
      o1Index: 22,
      o1Bid: "5d",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: 8,
      minNumC: "",
      maxNumC: "",
      o1Index: 22,
      o1Bid: "5d",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: 8,
      minNumC: 5,
      maxNumC: 5,
      o1Index: 22,
      o1Bid: "5d",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: 8,
      maxNumD: 8,
      minNumC: "",
      maxNumC: "",
      o1Index: 22,
      o1Bid: "5d",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: 8,
      minNumC: "",
      maxNumC: "",
      o1Index: 22,
      o1Bid: "5d",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: 8,
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      o1Index: 23,
      o1Bid: "4h",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: 8,
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      o1Index: 23,
      o1Bid: "4h",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: 5,
      maxNumS: 5,
      minNumH: 8,
      maxNumH: 8,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      o1Index: 23,
      o1Bid: "4h",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: 8,
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      o1Index: 23,
      o1Bid: "4h",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: 8,
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      o1Index: 23,
      o1Bid: "4h",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: 5,
      maxNumS: 5,
      minNumH: 8,
      maxNumH: 8,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      o1Index: 23,
      o1Bid: "4h",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: 8,
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      o1Index: 23,
      o1Bid: "4h",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: 8,
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      o1Index: 23,
      o1Bid: "4h",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: 5,
      maxNumS: 5,
      minNumH: 8,
      maxNumH: 8,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      o1Index: 23,
      o1Bid: "4h",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: 8,
      maxNumS: 8,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      o1Index: 24,
      o1Bid: "4s",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: 8,
      maxNumS: 8,
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      o1Index: 24,
      o1Bid: "4s",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: 8,
      maxNumS: 8,
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      o1Index: 24,
      o1Bid: "4s",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: 8,
      maxNumS: 8,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      o1Index: 24,
      o1Bid: "4s",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: 8,
      maxNumS: 8,
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      o1Index: 24,
      o1Bid: "4s",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: 8,
      maxNumS: 8,
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      o1Index: 24,
      o1Bid: "4s",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: 8,
      maxNumS: 8,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      o1Index: 24,
      o1Bid: "4s",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: 8,
      maxNumS: 8,
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      o1Index: 24,
      o1Bid: "4s",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: 8,
      maxNumS: 8,
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      o1Index: 24,
      o1Bid: "4s",
    },
  ];
  var rebid_ao1_85 = ao1_85.filter(
    (itemsInArray) =>
      hand.opStrength === itemsInArray.strength &&
      (hand.numS >= itemsInArray.minNumS || itemsInArray.minNumS === "") &&
      (hand.numS <= itemsInArray.maxNumS || itemsInArray.maxNumS === "") &&
      (hand.numH >= itemsInArray.minNumH || itemsInArray.minNumH === "") &&
      (hand.numH <= itemsInArray.maxNumH || itemsInArray.maxNumH === "") &&
      (hand.numD >= itemsInArray.minNumD || itemsInArray.minNumD === "") &&
      (hand.numD <= itemsInArray.maxNumD || itemsInArray.maxNumD === "") &&
      (hand.numC >= itemsInArray.minNumC || itemsInArray.minNumC === "") &&
      (hand.numC <= itemsInArray.maxNumC || itemsInArray.maxNumC === "")
  );
  return rebid_ao1_85;
}
