export default function (hand) {
  var fiveCard4Card4Card = [
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      numS: 5,
      numH: 4,
      numD: 4,
      numC: 0,
      o1Bid: "1s",
      hint: "12-19 points and 4 spade suit cards",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      numS: 5,
      numH: 4,
      numD: 4,
      numC: 0,
      o1Bid: "1s",
      hint: "12-19 points and 4 spade suit cards",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      numS: 5,
      numH: 4,
      numD: 4,
      numC: 0,
      o1Bid: "1s",
      hint: "12-19 points and 4 spade suit cards",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      numS: 5,
      numH: 4,
      numD: 0,
      numC: 4,
      o1Bid: "1s",
      hint: "12-19 points and 4 spade suit cards",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      numS: 5,
      numH: 4,
      numD: 0,
      numC: 4,
      o1Bid: "1s",
      hint: "12-19 points and 4 spade suit cards",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      numS: 5,
      numH: 4,
      numD: 0,
      numC: 4,
      o1Bid: "1s",
      hint: "12-19 points and 4 spade suit cards",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      numS: 5,
      numH: 0,
      numD: 4,
      numC: 4,
      o1Bid: "1s",
      hint: "12-19 points and 4 spade suit cards",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      numS: 5,
      numH: 0,
      numD: 4,
      numC: 4,
      o1Bid: "1s",
      hint: "12-19 points and 4 spade suit cards",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      numS: 5,
      numH: 0,
      numD: 4,
      numC: 4,
      o1Bid: "1s",
      hint: "12-19 points and 4+ spade suit cards",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      numS: 4,
      numH: 5,
      numD: 4,
      numC: 0,
      o1Bid: "1h",
      hint: "12-19 points and 4+ heart suit cards",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      numS: 4,
      numH: 5,
      numD: 4,
      numC: 0,
      o1Bid: "1h",
      hint: "12-19 points and 4+ heart suit cards",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      numS: 4,
      numH: 5,
      numD: 4,
      numC: 0,
      o1Bid: "1h",
      hint: "12-19 points and 4+ heart suit cards",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      numS: 4,
      numH: 5,
      numD: 0,
      numC: 4,
      o1Bid: "1h",
      hint: "12-19 points and 4+ heart suit cards",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      numS: 4,
      numH: 5,
      numD: 0,
      numC: 4,
      o1Bid: "1h",
      hint: "12-19 points and 4+ heart suit cards",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      numS: 4,
      numH: 5,
      numD: 0,
      numC: 4,
      o1Bid: "1h",
      hint: "12-19 points and 4+ heart suit cards",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      numS: 0,
      numH: 5,
      numD: 4,
      numC: 4,
      o1Bid: "1h",
      hint: "12-19 points and 4+ heart suit cards",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      numS: 0,
      numH: 5,
      numD: 4,
      numC: 4,
      o1Bid: "1h",
      hint: "12-19 points and 4+ heart suit cards",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      numS: 0,
      numH: 5,
      numD: 4,
      numC: 4,
      o1Bid: "1h",
      hint: "12-19 points and 4+ heart suit cards",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      numS: 4,
      numH: 4,
      numD: 5,
      numC: 0,
      o1Bid: "1d",
      hint: "12-19 points and 4+ diamond suit cards",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      numS: 4,
      numH: 4,
      numD: 5,
      numC: 0,
      o1Bid: "1d",
      hint: "12-19 points and 4+ diamond suit cards",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      numS: 4,
      numH: 4,
      numD: 5,
      numC: 0,
      o1Bid: "1d",
      hint: "12-19 points and 4+ diamond suit cards",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      numS: 4,
      numH: 0,
      numD: 5,
      numC: 4,
      o1Bid: "1d",
      hint: "12-19 points and 4+ diamond suit cards",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      numS: 4,
      numH: 0,
      numD: 5,
      numC: 4,
      o1Bid: "1d",
      hint: "12-19 points and 4+ diamond suit cards",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      numS: 4,
      numH: 0,
      numD: 5,
      numC: 4,
      o1Bid: "1d",
      hint: "12-19 points and 4+ diamond suit cards",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      numS: 0,
      numH: 4,
      numD: 5,
      numC: 4,
      o1Bid: "1d",
      hint: "12-19 points and 4+ diamond suit cards",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      numS: 0,
      numH: 4,
      numD: 5,
      numC: 4,
      o1Bid: "1d",
      hint: "12-19 points and 4+ diamond suit cards",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      numS: 0,
      numH: 4,
      numD: 5,
      numC: 4,
      o1Bid: "1d",
      hint: "12-19 points and 4+ diamond suit cards",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      numS: 0,
      numH: 4,
      numD: 4,
      numC: 5,
      o1Bid: "1c",
      hint: "12-19 points and 4+ club suit cards",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      numS: 0,
      numH: 4,
      numD: 4,
      numC: 5,
      o1Bid: "1c",
      hint: "12-19 points and 4+ club suit cards",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      numS: 0,
      numH: 4,
      numD: 4,
      numC: 5,
      o1Bid: "1c",
      hint: "12-19 points and 4+ club suit cards",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      numS: 4,
      numH: 4,
      numD: 0,
      numC: 5,
      o1Bid: "1c",
      hint: "12-19 points and 4+ club suit cards",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      numS: 4,
      numH: 4,
      numD: 0,
      numC: 5,
      o1Bid: "1c",
      hint: "12-19 points and 4+ club suit cards",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      numS: 4,
      numH: 4,
      numD: 0,
      numC: 5,
      o1Bid: "1c",
      hint: "12-19 points and 4+ club suit cards",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      numS: 4,
      numH: 0,
      numD: 4,
      numC: 5,
      o1Bid: "1c",
      hint: "12-19 points and 4+ club suit cards",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      numS: 4,
      numH: 0,
      numD: 4,
      numC: 5,
      o1Bid: "1c",
      hint: "12-19 points and 4+ club suit cards",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      numS: 4,
      numH: 0,
      numD: 4,
      numC: 5,
      o1Bid: "1c",
      hint: "12-19 points and 4+ club suit cards",
    },
  ];

  var rebidFiveCard4Card4Card = fiveCard4Card4Card.filter(
    (itemsInArray) =>
      hand.opStrength === itemsInArray.strength &&
      (hand.numS === itemsInArray.numS || itemsInArray.numS === "") &&
      (hand.numH === itemsInArray.numH || itemsInArray.numH === "") &&
      (hand.numD === itemsInArray.numD || itemsInArray.numD === "") &&
      (hand.numC === itemsInArray.numC || itemsInArray.numC === "") &&
      (hand.HCP >= itemsInArray.minTP || itemsInArray.minTP === "") &&
      (hand.HCP <= itemsInArray.maxTP || itemsInArray.maxTP === "")
  );
  return rebidFiveCard4Card4Card;
}
