export default function (hand) {
  var fiveCard4Card = [
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 5,
      maxNumC: 5,
      o1Bid: "1c",
      hint: "12-19 points and  4 club suit cards",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 5,
      maxNumC: 5,
      o1Bid: "1c",
      hint: "12-19 points and  4 club suit cards",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 5,
      maxNumC: 5,
      o1Bid: "1c",
      hint: "12-19 points and  4 club suit cards",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 5,
      maxNumC: 5,
      o1Bid: "1c",
      hint: "12-19 points and  4 club suit cards",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 5,
      maxNumC: 5,
      o1Bid: "1c",
      hint: "12-19 points and  4 club suit cards",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 5,
      maxNumC: 5,
      o1Bid: "1c",
      hint: "12-19 points and  4 club suit cards",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 5,
      maxNumC: 5,
      o1Bid: "1c",
      hint: "12-19 points and  4 club suit cards",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 5,
      maxNumC: 5,
      o1Bid: "1c",
      hint: "12-19 points and  4 club suit cards",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 5,
      maxNumC: 5,
      o1Bid: "1c",
      hint: "12-19 points and  4 club suit cards",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 5,
      maxNumD: 5,
      minNumC: 4,
      maxNumC: 4,
      o1Bid: "1d",
      hint: "12-19 points and  4 diamond suit cards",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 5,
      maxNumD: 5,
      minNumC: 4,
      maxNumC: 4,
      o1Bid: "1d",
      hint: "12-19 points and  4 diamond suit cards",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 5,
      maxNumD: 5,
      minNumC: 4,
      maxNumC: 4,
      o1Bid: "1d",
      hint: "12-19 points and  4 diamond suit cards",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 5,
      maxNumD: 5,
      minNumC: 4,
      maxNumC: 4,
      o1Bid: "1d",
      hint: "12-19 points and  4 diamond suit cards",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: 3,
      o1Bid: "1d",
      hint: "12-19 points and  4 diamond suit cards",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: 3,
      o1Bid: "1d",
      hint: "12-19 points and  4 diamond suit cards",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: 3,
      o1Bid: "1d",
      hint: "12-19 points and  4 diamond suit cards",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: 3,
      o1Bid: "1d",
      hint: "12-19 points and  4 diamond suit cards",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: 3,
      o1Bid: "1d",
      hint: "12-19 points and  4 diamond suit cards",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: 3,
      o1Bid: "1d",
      hint: "12-19 points and  4 diamond suit cards",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: "",
      maxNumS: 3,
      minNumH: 5,
      maxNumH: 5,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      o1Bid: "1h",
      hint: "12-19 points and  4 heart suit cards",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: 3,
      minNumH: 5,
      maxNumH: 5,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      o1Bid: "1h",
      hint: "12-19 points and  4 heart suit cards",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: 3,
      minNumH: 5,
      maxNumH: 5,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      o1Bid: "1h",
      hint: "12-19 points and  4 heart suit cards",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: "",
      maxNumS: 3,
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      o1Bid: "1h",
      hint: "12-19 points and  4 heart suit cards",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: 3,
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      o1Bid: "1h",
      hint: "12-19 points and  4 heart suit cards",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: 3,
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      o1Bid: "1h",
      hint: "12-19 points and  4 heart suit cards",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      o1Bid: "1h",
      hint: "12-19 points and  4 heart suit cards",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      o1Bid: "1h",
      hint: "12-19 points and  4 heart suit cards",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      o1Bid: "1h",
      hint: "12-19 points and  4 heart suit cards",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: 5,
      maxNumS: 5,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      o1Bid: "1s",
      hint: "12-19 points and  4 spade suit cards",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: 5,
      maxNumS: 5,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      o1Bid: "1s",
      hint: "12-19 points and  4 spade suit cards",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: 5,
      maxNumS: 5,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      o1Bid: "1s",
      hint: "12-19 points and  4 spade suit cards",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      o1Bid: "1s",
      hint: "12-19 points and  4 spade suit cards",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      o1Bid: "1s",
      hint: "12-19 points and  4 spade suit cards",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      o1Bid: "1s",
      hint: "12-19 points and  4 spade suit cards",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      o1Bid: "1s",
      hint: "12-19 points and  4 spade suit cards",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      o1Bid: "1s",
      hint: "12-19 points and  4 spade suit cards",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      o1Bid: "1s",
      hint: "12-19 points and  4 spade suit cards",
    },
  ];

  var rebidFiveCard4Card = fiveCard4Card.filter(
    (itemsInArray) =>
      hand.opStrength === itemsInArray.strength &&
      (hand.numS >= itemsInArray.minNumS || itemsInArray.minNumS === "") &&
      (hand.numS <= itemsInArray.maxNumS || itemsInArray.maxNumS === "") &&
      (hand.numH >= itemsInArray.minNumH || itemsInArray.minNumH === "") &&
      (hand.numH <= itemsInArray.maxNumH || itemsInArray.maxNumH === "") &&
      (hand.numD >= itemsInArray.minNumD || itemsInArray.minNumD === "") &&
      (hand.numD <= itemsInArray.maxNumD || itemsInArray.maxNumD === "") &&
      (hand.numC >= itemsInArray.minNumC || itemsInArray.minNumC === "") &&
      (hand.numC <= itemsInArray.maxNumC || itemsInArray.maxNumC === "") &&
      (hand.HCP >= itemsInArray.minTP || itemsInArray.minTP === "") &&
      (hand.HCP <= itemsInArray.maxTP || itemsInArray.maxTP === "")
  );

  return rebidFiveCard4Card;
}
