export default function (hand) {
  var fourCard4Card = [
    {
      bidder: "o1",
      minHCP: 12,
      maxHCP: 14,
      minTP: "",
      maxTP: "",
      strength: "o1NT",
      minNumS: 2,
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 2,
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      o1Bid: "1nt",
      hint: "12-14 points and 3 cards in every suit",
    },
    {
      bidder: "o1",
      minHCP: "",
      maxHCP: "",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      o1Bid: "1c",
      hint: "12-19 points and 4+ club suit cards",
    },
    {
      bidder: "o1",
      minHCP: "",
      maxHCP: "",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      o1Bid: "1c",
      hint: "12-19 points and 4+ club suit cards",
    },
    {
      bidder: "o1",
      minHCP: "",
      maxHCP: "",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      o1Bid: "1c",
      hint: "12-19 points and 4+ club suit cards",
    },
    {
      bidder: "o1",
      minHCP: 12,
      maxHCP: 14,
      minTP: "",
      maxTP: "",
      strength: "o1NT",
      minNumS: 2,
      maxNumS: 3,
      minNumH: 2,
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      o1Bid: "1nt",
      hint: "12-14 points and 3 cards in every suit",
    },
    {
      bidder: "o1",
      minHCP: "",
      maxHCP: "",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      o1Bid: "1c",
      hint: "12-19 points and 4+ club suit cards",
    },
    {
      bidder: "o1",
      minHCP: "",
      maxHCP: "",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      o1Bid: "1c",
      hint: "12-19 points and 4+ club suit cards",
    },
    {
      bidder: "o1",
      minHCP: "",
      maxHCP: "",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      o1Bid: "1c",
      hint: "12-19 points and 4+ club suit cards",
    },
    {
      bidder: "o1",
      minHCP: 12,
      maxHCP: 14,
      minTP: "",
      maxTP: "",
      strength: "o1NT",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 2,
      maxNumH: 3,
      minNumD: 2,
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      o1Bid: "1nt",
      hint: "12-14 points and 3 cards in every suit",
    },
    {
      bidder: "o1",
      minHCP: "",
      maxHCP: "",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      o1Bid: "1c",
      hint: "12-19 points and 4+ club suit cards",
    },
    {
      bidder: "o1",
      minHCP: "",
      maxHCP: "",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      o1Bid: "1c",
      hint: "12-19 points and 4+ club suit cards",
    },
    {
      bidder: "o1",
      minHCP: "",
      maxHCP: "",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      o1Bid: "1c",
      hint: "12-19 points and 4+ club suit cards",
    },
    {
      bidder: "o1",
      minHCP: 12,
      maxHCP: 14,
      minTP: "",
      maxTP: "",
      strength: "o1NT",
      minNumS: 2,
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 2,
      maxNumC: "",
      o1Bid: "1nt",
      hint: "12-14 points and 3 cards in every suit",
    },
    {
      bidder: "o1",
      minHCP: "",
      maxHCP: "",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      o1Bid: "1d",
      hint: "12-19 points and 4+ diamond suit cards",
    },
    {
      bidder: "o1",
      minHCP: "",
      maxHCP: "",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      o1Bid: "1d",
      hint: "12-19 points and 4+ diamond suit cards",
    },
    {
      bidder: "o1",
      minHCP: "",
      maxHCP: "",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      o1Bid: "1d",
      hint: "12-19 points and 4+ diamond suit cards",
    },
    {
      bidder: "o1",
      minHCP: 12,
      maxHCP: 14,
      minTP: "",
      maxTP: "",
      strength: "o1NT",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 2,
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: 2,
      maxNumC: "",
      o1Bid: "1nt",
      hint: "12-14 points and 3 cards in every suit",
    },
    {
      bidder: "o1",
      minHCP: "",
      maxHCP: "",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      o1Bid: "1d",
      hint: "12-19 points and 4+ diamond suit cards",
    },
    {
      bidder: "o1",
      minHCP: "",
      maxHCP: "",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      o1Bid: "1d",
      hint: "12-19 points and 4+ diamond suit cards",
    },
    {
      bidder: "o1",
      minHCP: "",
      maxHCP: "",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      o1Bid: "1d",
      hint: "12-19 points and 4+ diamond suit cards",
    },
    {
      bidder: "o1",
      minHCP: 12,
      maxHCP: 14,
      minTP: "",
      maxTP: "",
      strength: "o1NT",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 2,
      maxNumD: "",
      minNumC: 2,
      maxNumC: "",
      o1Bid: "1nt",
      hint: "12-14 points and 3 cards in every suit",
    },
    {
      bidder: "o1",
      minHCP: "",
      maxHCP: "",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      o1Bid: "1h",
      hint: "12-19 points and 4+ heart suit cards",
    },
    {
      bidder: "o1",
      minHCP: "",
      maxHCP: "",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      o1Bid: "1h",
      hint: "12-19 points and 4+ heart suit cards",
    },
    {
      bidder: "o1",
      minHCP: "",
      maxHCP: "",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      o1Bid: "1h",
      hint: "12-19 points and 4+ heart suit cards",
    },
  ];

  var rebidFourCard4Card = fourCard4Card.filter(
    (itemsInArray) =>
      hand.opStrength === itemsInArray.strength &&
      (hand.numS >= itemsInArray.minNumS || itemsInArray.minNumS === "") &&
      (hand.numS <= itemsInArray.maxNumS || itemsInArray.maxNumS === "") &&
      (hand.numH >= itemsInArray.minNumH || itemsInArray.minNumH === "") &&
      (hand.numH <= itemsInArray.maxNumH || itemsInArray.maxNumH === "") &&
      (hand.numD >= itemsInArray.minNumD || itemsInArray.minNumD === "") &&
      (hand.numD <= itemsInArray.maxNumD || itemsInArray.maxNumD === "") &&
      (hand.numC >= itemsInArray.minNumC || itemsInArray.minNumC === "") &&
      (hand.numC <= itemsInArray.maxNumC || itemsInArray.maxNumC === "") &&
      (hand.HCP >= itemsInArray.minHCP || itemsInArray.minHCP === "") &&
      (hand.HCP <= itemsInArray.maxHCP || itemsInArray.maxHCP === "") &&
      (hand.TP >= itemsInArray.minTP || itemsInArray.minTP === "") &&
      (hand.TP <= itemsInArray.maxTP || itemsInArray.maxTP === "")
  );
  return rebidFourCard4Card;
}
