export default function (hand) {
  var fourCard4Card4Card = [
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o1Bid: "1c",
      hint: "12-19 points and 4+ club suit cards",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o1Bid: "1c",
      hint: "12-19 points and 4+ club suit cards",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o1Bid: "1c",
      hint: "12-19 points and 4+ club suit cards",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o1Bid: "1d",
      hint: "12-19 points and 4+ diamond suit cards",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o1Bid: "1d",
      hint: "12-19 points and 4+ diamond suit cards",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o1Bid: "1d",
      hint: "12-19 points and 4+ diamond suit cards",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o1Bid: "1d",
      hint: "12-19 points and 4+ diamond suit cards",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o1Bid: "1d",
      hint: "12-19 points and 4+ diamond suit cards",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o1Bid: "1d",
      hint: "12-19 points and 4+ diamond suit cards",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o1Bid: "1c",
      hint: "12-19 points and 4+ club suit cards",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o1Bid: "1c",
      hint: "12-19 points and 4+ club suit cards",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o1Bid: "1c",
      hint: "12-19 points and 4+ club suit cards",
    },
  ];
  var rebidFourCard4Card4Card = fourCard4Card4Card.filter(
    (itemsInArray) =>
      hand.opStrength === itemsInArray.strength &&
      (hand.numS === itemsInArray.numS || itemsInArray.numS === "") &&
      (hand.numH === itemsInArray.numH || itemsInArray.numH === "") &&
      (hand.numD === itemsInArray.numD || itemsInArray.numD === "") &&
      (hand.numC === itemsInArray.numC || itemsInArray.numC === "") &&
      (hand.HCP >= itemsInArray.minTP || itemsInArray.minTP === "") &&
      (hand.HCP <= itemsInArray.maxTP || itemsInArray.maxTP === "")
  );

  return rebidFourCard4Card4Card;
}
