export default function (hand) {
  var ao1_76 = [
    {
      bidder: "oc1",
      weight: 1,
      minTP: 8,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 7,
      maxNumC: 7,
      o1Index: 1,
      o1Bid: "1c",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 8,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      o1Index: 1,
      o1Bid: "1c",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 8,
      maxTP: 9,
      strength: "min",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      o1Index: 1,
      o1Bid: "1c",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 7,
      maxNumC: 7,
      o1Index: 1,
      o1Bid: "1c",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      o1Index: 1,
      o1Bid: "1c",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      o1Index: 1,
      o1Bid: "1c",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 7,
      maxNumC: 7,
      o1Index: 1,
      o1Bid: "1c",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      o1Index: 1,
      o1Bid: "1c",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      o1Index: 1,
      o1Bid: "1c",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 8,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: 6,
      maxNumC: 6,
      o1Index: 2,
      o1Bid: "1d",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 8,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      o1Index: 2,
      o1Bid: "1d",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 8,
      maxTP: 9,
      strength: "min",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      o1Index: 2,
      o1Bid: "1d",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: 6,
      maxNumC: 6,
      o1Index: 2,
      o1Bid: "1d",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      o1Index: 2,
      o1Bid: "1d",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      o1Index: 2,
      o1Bid: "1d",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: 6,
      maxNumC: 6,
      o1Index: 2,
      o1Bid: "1d",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      o1Index: 2,
      o1Bid: "1d",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      o1Index: 2,
      o1Bid: "1d",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 8,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      o1Index: 3,
      o1Bid: "1h",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 8,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      o1Index: 3,
      o1Bid: "1h",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 8,
      maxTP: 9,
      strength: "min",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      o1Index: 3,
      o1Bid: "1h",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      o1Index: 3,
      o1Bid: "1h",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      o1Index: 3,
      o1Bid: "1h",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      o1Index: 3,
      o1Bid: "1h",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      o1Index: 3,
      o1Bid: "1h",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      o1Index: 3,
      o1Bid: "1h",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      o1Index: 3,
      o1Bid: "1h",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 8,
      maxTP: 9,
      strength: "min",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      o1Index: 4,
      o1Bid: "1s",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 8,
      maxTP: 9,
      strength: "min",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      o1Index: 4,
      o1Bid: "1s",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 8,
      maxTP: 9,
      strength: "min",
      minNumS: 7,
      maxNumS: 7,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      o1Index: 4,
      o1Bid: "1s",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      o1Index: 4,
      o1Bid: "1s",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      o1Index: 4,
      o1Bid: "1s",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 7,
      maxNumS: 7,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      o1Index: 4,
      o1Bid: "1s",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      o1Index: 4,
      o1Bid: "1s",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      o1Index: 4,
      o1Bid: "1s",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 7,
      maxNumS: 7,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      o1Index: 4,
      o1Bid: "1s",
    },
  ];
  var rebid_ao1_76 = ao1_76.filter(
    (itemsInArray) =>
      hand.ocStrength === itemsInArray.strength &&
      (hand.numS >= itemsInArray.minNumS || itemsInArray.minNumS === "") &&
      (hand.numS <= itemsInArray.maxNumS || itemsInArray.maxNumS === "") &&
      (hand.numH >= itemsInArray.minNumH || itemsInArray.minNumH === "") &&
      (hand.numH <= itemsInArray.maxNumH || itemsInArray.maxNumH === "") &&
      (hand.numD >= itemsInArray.minNumD || itemsInArray.minNumD === "") &&
      (hand.numD <= itemsInArray.maxNumD || itemsInArray.maxNumD === "") &&
      (hand.numC >= itemsInArray.minNumC || itemsInArray.minNumC === "") &&
      (hand.numC <= itemsInArray.maxNumC || itemsInArray.maxNumC === "")
  );
  return rebid_ao1_76;
}
