export default function (hand) {
  console.log("HAND STATS: ", hand);
  var oneLongSuit = [
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: "",
      o1Index: 1,
      o1Bid: "1c",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: "",
      o1Index: 1,
      o1Bid: "1c",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: "",
      o1Index: 1,
      o1Bid: "1c",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: "",
      minNumC: "",
      maxNumC: 3,
      o1Index: 2,
      o1Bid: "1d",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: "",
      minNumC: "",
      maxNumC: 3,
      o1Index: 2,
      o1Bid: "1d",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: "",
      minNumC: "",
      maxNumC: 3,
      o1Index: 2,
      o1Bid: "1d",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: "",
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      o1Index: 3,
      o1Bid: "1h",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: "",
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      o1Index: 3,
      o1Bid: "1h",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: "",
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      o1Index: 3,
      o1Bid: "1h",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: 4,
      maxNumS: "",
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      o1Index: 4,
      o1Bid: "1s",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: 4,
      maxNumS: "",
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      o1Index: 4,
      o1Bid: "1s",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: 4,
      maxNumS: "",
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      o1Index: 4,
      o1Bid: "1s",
    },
  ];
  var rebidOneLongSuit = oneLongSuit.filter(
    (itemsInArray) =>
      hand.opStrength === itemsInArray.strength &&
      (hand.numS >= itemsInArray.minNumS || itemsInArray.minNumS === "") &&
      (hand.numS <= itemsInArray.maxNumS || itemsInArray.maxNumS === "") &&
      (hand.numH >= itemsInArray.minNumH || itemsInArray.minNumH === "") &&
      (hand.numH <= itemsInArray.maxNumH || itemsInArray.maxNumH === "") &&
      (hand.numD >= itemsInArray.minNumD || itemsInArray.minNumD === "") &&
      (hand.numD <= itemsInArray.maxNumD || itemsInArray.maxNumD === "") &&
      (hand.numC >= itemsInArray.minNumC || itemsInArray.minNumC === "") &&
      (hand.numC <= itemsInArray.maxNumC || itemsInArray.maxNumC === "")
  );

  return rebidOneLongSuit;
}
