export default function (hand) {
  var sixCard6Card = [
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 6,
      maxNumC: 6,
      o1Bid: "1d",
      hint: "12-19 points and 4+ diamond cards",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 6,
      maxNumC: 6,
      o1Bid: "1d",
      hint: "12-19 points and 4+ diamond cards",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 6,
      maxNumC: 6,
      o1Bid: "1d",
      hint: "12-19 points and 4+ diamond cards",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      o1Bid: "1h",
      hint: "12-19 points and 4+  heart suit cards",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      o1Bid: "1h",
      hint: "12-19 points and 4+  heart suit cards",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      o1Bid: "1h",
      hint: "12-19 points and 4+  heart suit cards",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      o1Bid: "1h",
      hint: "12-19 points and 4+  heart suit cards",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      o1Bid: "1h",
      hint: "12-19 points and 4+  heart suit cards",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      o1Bid: "1h",
      hint: "12-19 points and 4+  heart suit cards",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      o1Bid: "1s",
      hint: "12-19 points and 4+  spade suit cards",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      o1Bid: "1s",
      hint: "12-19 points and 4+  spade suit cards",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      o1Bid: "1s",
      hint: "12-19 points and 4+  spade suit cards",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      o1Bid: "1s",
      hint: "12-19 points and 4+  spade suit cards",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      o1Bid: "1s",
      hint: "12-19 points and 4+  spade suit cards",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      o1Bid: "1s",
      hint: "12-19 points and 4+  spade suit cards",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      o1Bid: "1s",
      hint: "12-19 points and 4+  spade suit cards",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      o1Bid: "1s",
      hint: "12-19 points and 4+  spade suit cards",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      o1Bid: "1s",
      hint: "12-19 points and 4+  spade suit cards",
    },
  ];
  var rebidSixCard6Card = sixCard6Card.filter(
    (itemsInArray) =>
      hand.opStrength === itemsInArray.strength &&
      (hand.numS >= itemsInArray.minNumS || itemsInArray.minNumS === "") &&
      (hand.numS <= itemsInArray.maxNumS || itemsInArray.maxNumS === "") &&
      (hand.numH >= itemsInArray.minNumH || itemsInArray.minNumH === "") &&
      (hand.numH <= itemsInArray.maxNumH || itemsInArray.maxNumH === "") &&
      (hand.numD >= itemsInArray.minNumD || itemsInArray.minNumD === "") &&
      (hand.numD <= itemsInArray.maxNumD || itemsInArray.maxNumD === "") &&
      (hand.numC >= itemsInArray.minNumC || itemsInArray.minNumC === "") &&
      (hand.numC <= itemsInArray.maxNumC || itemsInArray.maxNumC === "") &&
      (hand.HCP >= itemsInArray.minTP || itemsInArray.minTP === "") &&
      (hand.HCP <= itemsInArray.maxTP || itemsInArray.maxTP === "")
  );

  return rebidSixCard6Card;
}
