export default function (hand) {
  var ao1_84 = [
    {
      bidder: "o1",
      weight: 1,
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: 8,
      maxNumC: 8,
      o1bIndex: 21,
      o1Bid: "5c",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: 8,
      maxNumC: 8,
      o1bIndex: 21,
      o1Bid: "5c",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: 8,
      maxNumC: 8,
      o1bIndex: 21,
      o1Bid: "5c",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: 8,
      o1bIndex: 21,
      o1Bid: "5c",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: 8,
      o1bIndex: 21,
      o1Bid: "5c",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: 8,
      o1bIndex: 21,
      o1Bid: "5c",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: 8,
      o1bIndex: 21,
      o1Bid: "5c",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: 8,
      o1bIndex: 21,
      o1Bid: "5c",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: 8,
      o1bIndex: 21,
      o1Bid: "5c",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: 8,
      minNumC: 4,
      maxNumC: 4,
      o1bIndex: 22,
      o1Bid: "5d",
    },
    {
      bidder: "o1",
      weight: 2,
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: 8,
      minNumC: 4,
      maxNumC: 4,
      o1bIndex: 22,
      o1Bid: "5d",
    },
    {
      bidder: "o1",
      weight: 2,
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: 8,
      minNumC: 4,
      maxNumC: 4,
      o1bIndex: 22,
      o1Bid: "5d",
    },
    {
      bidder: "o1",
      weight: 2,
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: 8,
      maxNumD: 8,
      minNumC: "",
      maxNumC: "",
      o1bIndex: 22,
      o1Bid: "5d",
    },
    {
      bidder: "o1",
      weight: 2,
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: 8,
      maxNumD: 8,
      minNumC: "",
      maxNumC: "",
      o1bIndex: 22,
      o1Bid: "5d",
    },
    {
      bidder: "o1",
      weight: 2,
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: 8,
      maxNumD: 8,
      minNumC: "",
      maxNumC: "",
      o1bIndex: 22,
      o1Bid: "5d",
    },
    {
      bidder: "o1",
      weight: 2,
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: 8,
      minNumC: "",
      maxNumC: "",
      o1bIndex: 22,
      o1Bid: "5d",
    },
    {
      bidder: "o1",
      weight: 2,
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: 8,
      minNumC: "",
      maxNumC: "",
      o1bIndex: 22,
      o1Bid: "5d",
    },
    {
      bidder: "o1",
      weight: 2,
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: 8,
      minNumC: "",
      maxNumC: "",
      o1bIndex: 22,
      o1Bid: "5d",
    },
    {
      bidder: "o1",
      weight: 2,
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: 8,
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      o1bIndex: 23,
      o1Bid: "4h",
    },
    {
      bidder: "o1",
      weight: 2,
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: 8,
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      o1bIndex: 23,
      o1Bid: "4h",
    },
    {
      bidder: "o1",
      weight: 2,
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: 8,
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      o1bIndex: 23,
      o1Bid: "4h",
    },
    {
      bidder: "o1",
      weight: 2,
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: 8,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      o1bIndex: 23,
      o1Bid: "4h",
    },
    {
      bidder: "o1",
      weight: 2,
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: 8,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      o1bIndex: 23,
      o1Bid: "4h",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: 8,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      o1bIndex: 23,
      o1Bid: "4h",
    },
    {
      bidder: "o1",
      weight: 2,
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 8,
      maxNumH: 8,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      o1bIndex: 23,
      o1Bid: "4h",
    },
    {
      bidder: "o1",
      weight: 2,
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 8,
      maxNumH: 8,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      o1bIndex: 23,
      o1Bid: "4h",
    },
    {
      bidder: "o1",
      weight: 2,
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 8,
      maxNumH: 8,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      o1bIndex: 23,
      o1Bid: "4h",
    },
    {
      bidder: "o1",
      weight: 2,
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: 8,
      maxNumS: 8,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      o1bIndex: 24,
      o1Bid: "4s",
    },
    {
      bidder: "o1",
      weight: 2,
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: 8,
      maxNumS: 8,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      o1bIndex: 24,
      o1Bid: "4s",
    },
    {
      bidder: "o1",
      weight: 2,
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: 8,
      maxNumS: 8,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      o1bIndex: 24,
      o1Bid: "4s",
    },
    {
      bidder: "o1",
      weight: 2,
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: 8,
      maxNumS: 8,
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      o1bIndex: 24,
      o1Bid: "4s",
    },
    {
      bidder: "o1",
      weight: 2,
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: 8,
      maxNumS: 8,
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      o1bIndex: 24,
      o1Bid: "4s",
    },
    {
      bidder: "o1",
      weight: 2,
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: 8,
      maxNumS: 8,
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      o1bIndex: 24,
      o1Bid: "4s",
    },
    {
      bidder: "o1",
      weight: 2,
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: 8,
      maxNumS: 8,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      o1bIndex: 24,
      o1Bid: "4s",
    },
    {
      bidder: "o1",
      weight: 2,
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: 8,
      maxNumS: 8,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      o1bIndex: 24,
      o1Bid: "4s",
    },
    {
      bidder: "o1",
      weight: 2,
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: 8,
      maxNumS: 8,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      o1bIndex: 24,
      o1Bid: "4s",
    },
  ];
  var rebid_ao1_84 = ao1_84.filter(
    (itemsInArray) =>
      hand.opStrength === itemsInArray.strength &&
      (hand.numS >= itemsInArray.minNumS || itemsInArray.minNumS === "") &&
      (hand.numS <= itemsInArray.maxNumS || itemsInArray.maxNumS === "") &&
      (hand.numH >= itemsInArray.minNumH || itemsInArray.minNumH === "") &&
      (hand.numH <= itemsInArray.maxNumH || itemsInArray.maxNumH === "") &&
      (hand.numD >= itemsInArray.minNumD || itemsInArray.minNumD === "") &&
      (hand.numD <= itemsInArray.maxNumD || itemsInArray.maxNumD === "") &&
      (hand.numC >= itemsInArray.minNumC || itemsInArray.minNumC === "") &&
      (hand.numC <= itemsInArray.maxNumC || itemsInArray.maxNumC === "")
  );
  return rebid_ao1_84;
}
