export default function (hand) {
  var fiveCard5Card = [
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: 5,
      maxNumS: 5,
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      o1Bid: "1s",
      hint: "12-19 points and 4+ cards in spades",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: 5,
      maxNumS: 5,
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      o1Bid: "1s",
      hint: "12-19 points and 4+ cards in spades",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 18,
      strength: "max",
      minNumS: 5,
      maxNumS: 5,
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      o1Bid: "1s",
      hint: "12-19 points and 4+ cards in spades",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: 3,
      o1Bid: "1s",
      hint: "12-19 points and 4+ cards in spades",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: 3,
      o1Bid: "1s",
      hint: "12-19 points and 4+ cards in spades",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 18,
      strength: "max",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: 3,
      o1Bid: "1s",
      hint: "12-19 points and 4+ cards in spades",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      o1Bid: "1s",
      hint: "12-19 points and 4+ cards in spades",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      o1Bid: "1s",
      hint: "12-19 points and 4+ cards in spades",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 18,
      strength: "max",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      o1Bid: "1s",
      hint: "12-19 points and 4+ cards in spades",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: 3,
      o1Bid: "1h",
      hint: "12-19 points and 4+ cards in hearts",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: 3,
      o1Bid: "1h",
      hint: "12-19 points and 4+ cards in hearts",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 18,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: 3,
      o1Bid: "1h",
      hint: "12-19 points and 4+ cards in hearts",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      o1Bid: "1h",
      hint: "12-19 points and 4+ cards in hearts",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      o1Bid: "1h",
      hint: "12-19 points and 4+ cards in hearts",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 18,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      o1Bid: "1h",
      hint: "12-19 points and 4+ cards in hearts",
    },
    {
      bidder: "o1",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: 5,
      maxNumC: 5,
      o1Bid: "1d",
      hint: "12-19 points and 4+ diamond suit cards",
    },
    {
      bidder: "o1",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: 5,
      maxNumC: 5,
      o1Bid: "1d",
      hint: "12-19 points and 4+ diamond suit cards",
    },
    {
      bidder: "o1",
      minTP: 17,
      maxTP: 18,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: 5,
      maxNumC: 5,
      o1Bid: "1d",
      hint: "12-19 points and 4+ diamond suit cards",
    },
  ];
  var rebidFiveCard5Card = fiveCard5Card.filter(
    (itemsInArray) =>
      hand.opStrength === itemsInArray.strength &&
      (hand.numS >= itemsInArray.minNumS || itemsInArray.minNumS === "") &&
      (hand.numS <= itemsInArray.maxNumS || itemsInArray.maxNumS === "") &&
      (hand.numH >= itemsInArray.minNumH || itemsInArray.minNumH === "") &&
      (hand.numH <= itemsInArray.maxNumH || itemsInArray.maxNumH === "") &&
      (hand.numD >= itemsInArray.minNumD || itemsInArray.minNumD === "") &&
      (hand.numD <= itemsInArray.maxNumD || itemsInArray.maxNumD === "") &&
      (hand.numC >= itemsInArray.minNumC || itemsInArray.minNumC === "") &&
      (hand.numC <= itemsInArray.maxNumC || itemsInArray.maxNumC === "") &&
      (hand.HCP >= itemsInArray.minTP || itemsInArray.minTP === "") &&
      (hand.HCP <= itemsInArray.maxTP || itemsInArray.maxTP === "")
  );
  return rebidFiveCard5Card;
}
