export default function (hand) {
  var ao1_74 = [
    {
      bidder: "o1",
      weight: 1,
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: 7,
      maxNumC: 7,
      o1Index: 1,
      o1Bid: "1c",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      o1Index: 1,
      o1Bid: "1c",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      o1Index: 1,
      o1Bid: "1c",
    },
    {
      bidder: "o1",
      weight: 2,
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      o1Index: 1,
      o1Bid: "1c",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: 7,
      maxNumC: 7,
      o1Index: 1,
      o1Bid: "1c",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      o1Index: 1,
      o1Bid: "1c",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      o1Index: 1,
      o1Bid: "1c",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: 7,
      maxNumC: 7,
      o1Index: 1,
      o1Bid: "1c",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      o1Index: 1,
      o1Bid: "1c",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      o1Index: 1,
      o1Bid: "1c",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: 4,
      maxNumC: 4,
      o1Index: 2,
      o1Bid: "1d",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      o1Index: 2,
      o1Bid: "1d",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      o1Index: 2,
      o1Bid: "1d",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: 4,
      maxNumC: 4,
      o1Index: 2,
      o1Bid: "1d",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      o1Index: 2,
      o1Bid: "1d",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      o1Index: 2,
      o1Bid: "1d",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: 4,
      maxNumC: 4,
      o1Index: 2,
      o1Bid: "1d",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      o1Index: 2,
      o1Bid: "1d",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      o1Index: 2,
      o1Bid: "1d",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      o1Index: 3,
      o1Bid: "1h",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      o1Index: 3,
      o1Bid: "1h",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      o1Index: 3,
      o1Bid: "1h",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      o1Index: 3,
      o1Bid: "1h",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      o1Index: 3,
      o1Bid: "1h",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      o1Index: 3,
      o1Bid: "1h",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      o1Index: 3,
      o1Bid: "1h",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      o1Index: 3,
      o1Bid: "1h",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      o1Index: 3,
      o1Bid: "1h",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      o1Index: 4,
      o1Bid: "1s",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      o1Index: 4,
      o1Bid: "1s",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 12,
      maxTP: 14,
      strength: "min",
      minNumS: 7,
      maxNumS: 7,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      o1Index: 4,
      o1Bid: "1s",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      o1Index: 4,
      o1Bid: "1s",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      o1Index: 4,
      o1Bid: "1s",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 15,
      maxTP: 16,
      strength: "med",
      minNumS: 7,
      maxNumS: 7,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      o1Index: 4,
      o1Bid: "1s",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      o1Index: 4,
      o1Bid: "1s",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      o1Index: 4,
      o1Bid: "1s",
    },
    {
      bidder: "o1",
      weight: 1,
      minTP: 17,
      maxTP: 19,
      strength: "max",
      minNumS: 7,
      maxNumS: 7,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      o1Index: 4,
      o1Bid: "1s",
    },
  ];
  var rebid_ao1_74 = ao1_74.filter(
    (itemsInArray) =>
      hand.opStrength === itemsInArray.strength &&
      (hand.numS >= itemsInArray.minNumS || itemsInArray.minNumS === "") &&
      (hand.numS <= itemsInArray.maxNumS || itemsInArray.maxNumS === "") &&
      (hand.numH >= itemsInArray.minNumH || itemsInArray.minNumH === "") &&
      (hand.numH <= itemsInArray.maxNumH || itemsInArray.maxNumH === "") &&
      (hand.numD >= itemsInArray.minNumD || itemsInArray.minNumD === "") &&
      (hand.numD <= itemsInArray.maxNumD || itemsInArray.maxNumD === "") &&
      (hand.numC >= itemsInArray.minNumC || itemsInArray.minNumC === "") &&
      (hand.numC <= itemsInArray.maxNumC || itemsInArray.maxNumC === "")
  );
  return rebid_ao1_74;
}
