export default function (hand, o1Bid, oc1Bid) {
  var fourCard4Card4Card = [
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 4,
      r1Index: 2,
      r1Bid: "1d",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 3,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 2,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 3,
      r1Index: 2,
      r1Bid: "1d",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 2,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 3,
      r1Index: 7,
      r1Bid: "2d",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 2,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 4,
      r1Index: 2,
      r1Bid: "1d",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 3,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 2,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 3,
      r1Index: 2,
      r1Bid: "1d",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 11,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 3,
      r1Index: 7,
      r1Bid: "2d",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 2,
      r1Index: 14,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 16,
      r1Bid: "4c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 1,
      maxNumD: 1,
      minNumC: 4,
      maxNumC: 4,
      weight: 4,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 1,
      maxNumD: 1,
      minNumC: 4,
      maxNumC: 4,
      weight: 3,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 1,
      maxNumD: 1,
      minNumC: 4,
      maxNumC: 4,
      weight: 2,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 1,
      maxNumD: 1,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 1,
      maxNumD: 1,
      minNumC: 4,
      maxNumC: 4,
      weight: 3,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 1,
      maxNumD: 1,
      minNumC: 4,
      maxNumC: 4,
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 1,
      maxNumD: 1,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 11,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 1,
      maxNumD: 1,
      minNumC: 4,
      maxNumC: 4,
      weight: 3,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 1,
      maxNumD: 1,
      minNumC: 4,
      maxNumC: 4,
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 1,
      maxNumD: 1,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 1,
      maxNumC: 1,
      weight: 4,
      r1Index: 2,
      r1Bid: "1d",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 1,
      maxNumC: 1,
      weight: 3,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 1,
      maxNumC: 1,
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 1,
      maxNumC: 1,
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 1,
      maxNumC: 1,
      weight: 3,
      r1Index: 2,
      r1Bid: "1d",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 1,
      maxNumC: 1,
      weight: 2,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 1,
      maxNumC: 1,
      weight: 1,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 2,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 4,
      r1Index: 2,
      r1Bid: "1d",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 3,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 2,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 7,
      r1Bid: "2d",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 2,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 3,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 2,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 7,
      r1Bid: "2d",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 3,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 2,
      r1Index: 11,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 12,
      r1Bid: "3d",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 4,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 3,
      r1Index: 11,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 2,
      r1Index: 14,
      r1Bid: "3s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 1,
      maxNumD: 1,
      minNumC: 4,
      maxNumC: 4,
      weight: 3,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 1,
      maxNumD: 1,
      minNumC: 4,
      maxNumC: 4,
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 1,
      maxNumD: 1,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 1,
      maxNumD: 1,
      minNumC: 4,
      maxNumC: 4,
      weight: 4,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 1,
      maxNumD: 1,
      minNumC: 4,
      maxNumC: 4,
      weight: 3,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 1,
      maxNumD: 1,
      minNumC: 4,
      maxNumC: 4,
      weight: 2,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 1,
      maxNumD: 1,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 1,
      maxNumD: 1,
      minNumC: 4,
      maxNumC: 4,
      weight: 2,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 1,
      maxNumD: 1,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 1,
      maxNumC: 1,
      weight: 4,
      r1Index: 2,
      r1Bid: "1d",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 1,
      maxNumC: 1,
      weight: 3,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 1,
      maxNumC: 1,
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 1,
      maxNumC: 1,
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 1,
      maxNumC: 1,
      weight: 3,
      r1Index: 2,
      r1Bid: "1d",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 1,
      maxNumC: 1,
      weight: 2,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 1,
      maxNumC: 1,
      weight: 1,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 1,
      maxNumC: 1,
      weight: 3,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 1,
      maxNumC: 1,
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 1,
      maxNumC: 1,
      weight: 1,
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 13,
      r1Bid: "3h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 3,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 2,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 7,
      r1Bid: "2d",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 3,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 2,
      r1Index: 11,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 12,
      r1Bid: "3d",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 1,
      maxNumD: 1,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 1,
      maxNumD: 1,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 13,
      r1Bid: "3h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 1,
      maxNumD: 1,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 1,
      maxNumC: 1,
      weight: 1,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 1,
      maxNumC: 1,
      weight: 1,
      r1Index: 13,
      r1Bid: "3h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 1,
      maxNumC: 1,
      weight: 1,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 3,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 2,
      r1Index: 7,
      r1Bid: "2d",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 4,
      r1Index: 11,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 3,
      r1Index: 12,
      r1Bid: "3d",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 2,
      r1Index: 13,
      r1Bid: "3h",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 3,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 2,
      r1Index: 7,
      r1Bid: "2d",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 3,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 2,
      r1Index: 11,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 12,
      r1Bid: "3d",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 1,
      maxNumD: 1,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 1,
      maxNumD: 1,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 14,
      r1Bid: "3s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 1,
      maxNumD: 1,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 18,
      r1Bid: "4s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 1,
      maxNumC: 1,
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 1,
      maxNumC: 1,
      weight: 1,
      r1Index: 14,
      r1Bid: "3s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 1,
      maxNumC: 1,
      weight: 1,
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 6,
      o1Bid: "2c",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 11,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 6,
      o1Bid: "2c",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 3,
      r1Index: 7,
      r1Bid: "2d",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 6,
      o1Bid: "2c",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 2,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 6,
      o1Bid: "2c",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 16,
      r1Bid: "4c",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 6,
      o1Bid: "2c",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 26,
      r1Bid: "6c",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 6,
      o1Bid: "2c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 3,
      r1Index: 7,
      r1Bid: "2d",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 6,
      o1Bid: "2c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 2,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 6,
      o1Bid: "2c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 6,
      o1Bid: "2c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 2,
      r1Index: 12,
      r1Bid: "3d",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 6,
      o1Bid: "2c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 26,
      r1Bid: "6c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 6,
      o1Bid: "2c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 1,
      maxNumD: 1,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 11,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 6,
      o1Bid: "2c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 1,
      maxNumD: 1,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 6,
      o1Bid: "2c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 1,
      maxNumD: 1,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 26,
      r1Bid: "6c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 7,
      o1Bid: "2d",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 12,
      r1Bid: "3d",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 7,
      o1Bid: "2d",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 2,
      r1Index: 11,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 7,
      o1Bid: "2d",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 13,
      r1Bid: "3h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 7,
      o1Bid: "2d",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 27,
      r1Bid: "6d",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 7,
      o1Bid: "2d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 7,
      o1Bid: "2d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 3,
      r1Index: 11,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 7,
      o1Bid: "2d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 2,
      r1Index: 14,
      r1Bid: "3s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 7,
      o1Bid: "2d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 17,
      r1Bid: "5d",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 7,
      o1Bid: "2d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 22,
      r1Bid: "6d",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 7,
      o1Bid: "2d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 1,
      maxNumC: 1,
      weight: 1,
      r1Index: 12,
      r1Bid: "3d",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 7,
      o1Bid: "2d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 1,
      maxNumC: 1,
      weight: 1,
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 7,
      o1Bid: "2d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 1,
      maxNumC: 1,
      weight: 1,
      r1Index: 27,
      r1Bid: "6d",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 8,
      o1Bid: "2h",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 8,
      o1Bid: "2h",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 28,
      r1Bid: "6h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 8,
      o1Bid: "2h",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 28,
      r1Bid: "6h",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 8,
      o1Bid: "2h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 8,
      o1Bid: "2h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 8,
      o1Bid: "2h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 8,
      o1Bid: "2h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 1,
      maxNumD: 1,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 13,
      r1Bid: "3h",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 8,
      o1Bid: "2h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 1,
      maxNumD: 1,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 8,
      o1Bid: "2h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 1,
      maxNumD: 1,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 28,
      r1Bid: "6h",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 8,
      o1Bid: "2h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 1,
      maxNumC: 1,
      weight: 1,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 8,
      o1Bid: "2h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 1,
      maxNumC: 1,
      weight: 1,
      r1Index: 28,
      r1Bid: "6h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 8,
      o1Bid: "2h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 1,
      maxNumC: 1,
      weight: 1,
      r1Index: 33,
      r1Bid: "7h",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 9,
      o1Bid: "2s",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 3,
      r1Index: 11,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 9,
      o1Bid: "2s",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 2,
      r1Index: 12,
      r1Bid: "3d",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 9,
      o1Bid: "2s",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 13,
      r1Bid: "3h",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 9,
      o1Bid: "2s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 14,
      r1Bid: "3s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 9,
      o1Bid: "2s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 9,
      o1Bid: "2s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 29,
      r1Bid: "6s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 9,
      o1Bid: "2s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 1,
      maxNumD: 1,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 19,
      r1Bid: "3s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 9,
      o1Bid: "2s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 1,
      maxNumD: 1,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 9,
      o1Bid: "2s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 1,
      maxNumD: 1,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 29,
      r1Bid: "6s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 9,
      o1Bid: "2s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 1,
      maxNumC: 1,
      weight: 1,
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 9,
      o1Bid: "2s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 1,
      maxNumC: 1,
      weight: 1,
      r1Index: 29,
      r1Bid: "6s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 9,
      o1Bid: "2s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 1,
      maxNumC: 1,
      weight: 1,
      r1Index: 34,
      r1Bid: "7s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 11,
      o1Bid: "3c",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 26,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 11,
      o1Bid: "3c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 26,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 11,
      o1Bid: "3c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 1,
      maxNumD: 1,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 12,
      o1Bid: "3d",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 27,
      r1Bid: "5d",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 12,
      o1Bid: "3d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 27,
      r1Bid: "5d",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 12,
      o1Bid: "3d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 1,
      maxNumC: 1,
      weight: 1,
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 13,
      o1Bid: "3h",
      minNumS: 1,
      maxNumS: 1,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 13,
      o1Bid: "3h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 13,
      o1Bid: "3h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 1,
      maxNumD: 1,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 13,
      o1Bid: "3h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 1,
      maxNumC: 1,
      weight: 1,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 14,
      o1Bid: "3s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 1,
      maxNumH: 1,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 14,
      o1Bid: "3s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 1,
      maxNumD: 1,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 14,
      o1Bid: "3s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 1,
      maxNumC: 1,
      weight: 1,
      r1Index: 19,
      r1Bid: "4s",
    },
  ];
  var rebidFourCard4Card4Card = fourCard4Card4Card.filter(
    (itemsInArray) =>
      hand.reStrength === itemsInArray.strength &&
      (hand.numS >= itemsInArray.minNumS || itemsInArray.minNumS === "") &&
      (hand.numS <= itemsInArray.maxNumS || itemsInArray.maxNumS === "") &&
      (hand.numH >= itemsInArray.minNumH || itemsInArray.minNumH === "") &&
      (hand.numH <= itemsInArray.maxNumH || itemsInArray.maxNumH === "") &&
      (hand.numD >= itemsInArray.minNumD || itemsInArray.minNumD === "") &&
      (hand.numD <= itemsInArray.maxNumD || itemsInArray.maxNumD === "") &&
      (hand.numC >= itemsInArray.minNumC || itemsInArray.minNumC === "") &&
      (hand.numC <= itemsInArray.maxNumC || itemsInArray.maxNumC === "") &&
      o1Bid === itemsInArray.o1Bid
  );
  return rebidFourCard4Card4Card;
}
