export default function (hand, o1Bid) {
  var eightCard4Card = [
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 8,
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: 3,
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r2",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 8,
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: 3,
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 8,
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: 3,
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 8,
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r2",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 8,
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 8,
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 8,
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r2",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 8,
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 8,
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 8,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 11,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 8,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 8,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r2",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: 8,
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r2",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: 8,
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: 8,
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r2",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: "",
      r1Index: 26,
      r1Bid: "6c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: "",
      r1Index: 26,
      r1Bid: "6c",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: "",
      r1Index: 26,
      r1Bid: "6c",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: "",
      r1Index: 26,
      r1Bid: "6c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: "",
      r1Index: 26,
      r1Bid: "6c",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: "",
      r1Index: 26,
      r1Bid: "6c",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: "",
      r1Index: 26,
      r1Bid: "6c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: 8,
      maxNumC: "",
      r1Index: 26,
      r1Bid: "6c",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: 8,
      maxNumC: "",
      r1Index: 26,
      r1Bid: "6c",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: 8,
      maxNumC: "",
      r1Index: 26,
      r1Bid: "6c",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 8,
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r2",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 8,
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 8,
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 8,
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r2",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 8,
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 8,
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 8,
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r2",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 8,
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 8,
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 8,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 8,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 27,
      r1Bid: "6d",
    },
    {
      bidder: "r2",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 27,
      r1Bid: "6d",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 27,
      r1Bid: "6d",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: 8,
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 27,
      r1Bid: "6d",
    },
    {
      bidder: "r2",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: 8,
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 27,
      r1Bid: "6d",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: 8,
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 27,
      r1Bid: "6d",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 27,
      r1Bid: "6d",
    },
    {
      bidder: "r2",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 27,
      r1Bid: "6d",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 27,
      r1Bid: "6d",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: "",
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: "",
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: "",
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: "",
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: "",
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: "",
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: 8,
      maxNumC: "",
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: 8,
      maxNumC: "",
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: 8,
      maxNumC: "",
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 8,
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: "",
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r2",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 8,
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: "",
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 8,
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 8,
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r2",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 8,
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 8,
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 8,
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r2",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 8,
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 8,
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 8,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 28,
      r1Bid: "6h",
    },
    {
      bidder: "r2",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 8,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 28,
      r1Bid: "6h",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 8,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 28,
      r1Bid: "6h",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      r1Index: 28,
      r1Bid: "6h",
    },
    {
      bidder: "r2",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      r1Index: 28,
      r1Bid: "6h",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      r1Index: 28,
      r1Bid: "6h",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 28,
      r1Bid: "6h",
    },
    {
      bidder: "r2",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 28,
      r1Bid: "6h",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 28,
      r1Bid: "6h",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r2",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: 8,
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r2",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: 8,
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: 8,
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r2",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: 8,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: 8,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: 8,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: 8,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: 8,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: 8,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: 8,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: 8,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: 8,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: 8,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: 8,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: 8,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: 8,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: 8,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: 8,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: 8,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: 8,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: 8,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: "",
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: 8,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: 8,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: "",
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: 8,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: 8,
      maxNumC: 8,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: 8,
      maxNumC: "",
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: 8,
      maxNumC: 8,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 8,
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 29,
      r1Bid: "6s",
    },
    {
      bidder: "r2",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 8,
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 29,
      r1Bid: "6s",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 8,
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 29,
      r1Bid: "6s",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 8,
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      r1Index: 29,
      r1Bid: "6s",
    },
    {
      bidder: "r2",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 8,
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      r1Index: 29,
      r1Bid: "6s",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 8,
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      r1Index: 29,
      r1Bid: "6s",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 8,
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 29,
      r1Bid: "6s",
    },
    {
      bidder: "r2",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 8,
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 29,
      r1Bid: "6s",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 8,
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 29,
      r1Bid: "6s",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 8,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 8,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 8,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: "",
      maxNumS: "",
      minNumH: 8,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r2",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: 8,
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r2",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: 8,
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: 8,
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r2",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r2",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r2",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 8,
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: "",
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: "",
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: "",
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: "",
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: 8,
      maxNumC: "",
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 8,
      maxNumC: "",
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 8,
      maxNumC: "",
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 8,
      maxNumC: "",
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 8,
      maxNumC: "",
      r1Index: 21,
      r1Bid: "5c",
    },
  ];

  var rebid8Card4Card = eightCard4Card.filter(
    (itemsInArray) =>
      hand.reStrength === itemsInArray.strength &&
      (hand.numS >= itemsInArray.minNumS || itemsInArray.minNumS === "") &&
      (hand.numS <= itemsInArray.maxNumS || itemsInArray.maxNumS === "") &&
      (hand.numH >= itemsInArray.minNumH || itemsInArray.minNumH === "") &&
      (hand.numH <= itemsInArray.maxNumH || itemsInArray.maxNumH === "") &&
      (hand.numD >= itemsInArray.minNumD || itemsInArray.minNumD === "") &&
      (hand.numD <= itemsInArray.maxNumD || itemsInArray.maxNumD === "") &&
      (hand.numC >= itemsInArray.minNumC || itemsInArray.minNumC === "") &&
      (hand.numC <= itemsInArray.maxNumC || itemsInArray.maxNumC === "") &&
      o1Bid === itemsInArray.o1Bid
  );
  return rebid8Card4Card;
}
