export default function (hand, o1Bid, oc1Bid) {
  var ar1_76 = [
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 2,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 1,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 2,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 1,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 2,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 1,
      r1Index: 26,
      r1Bid: "6c",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 2,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 1,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 2,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 1,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 2,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 1,
      r1Index: 26,
      r1Bid: "6c",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 7,
      maxNumC: 7,
      weight: 2,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 7,
      maxNumC: 7,
      weight: 1,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 7,
      maxNumC: 7,
      weight: 2,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 7,
      maxNumC: 7,
      weight: 1,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 7,
      maxNumC: 7,
      weight: 2,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 7,
      maxNumC: 7,
      weight: 1,
      r1Index: 26,
      r1Bid: "6c",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: 6,
      maxNumC: 6,
      weight: 2,
      r1Index: 2,
      r1Bid: "1d",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: 6,
      maxNumC: 6,
      weight: 2,
      r1Index: 2,
      r1Bid: "1d",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 11,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: 6,
      maxNumC: 6,
      weight: 2,
      r1Index: 7,
      r1Bid: "2d",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 12,
      r1Bid: "3d",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 2,
      r1Bid: "1d",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 2,
      r1Bid: "1d",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 11,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 2,
      r1Bid: "1d",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 12,
      r1Bid: "3d",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 2,
      r1Bid: "1d",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 2,
      r1Bid: "1d",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 11,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 2,
      r1Bid: "1d",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 12,
      r1Bid: "3d",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 13,
      r1Bid: "3h",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 2,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 2,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 2,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: 7,
      maxNumS: 7,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: 7,
      maxNumS: 7,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 7,
      maxNumS: 7,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 7,
      maxNumS: 7,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 7,
      maxNumS: 7,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 7,
      maxNumS: 7,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 13,
      r1Bid: "3h",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 7,
      r1Bid: "2d",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 12,
      r1Bid: "3d",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 11,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 2,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      o1Index: 1,
      o1Bid: "1c",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 1,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 2,
      r1Index: 11,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 1,
      r1Index: 14,
      r1Bid: "3s",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 2,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 1,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 2,
      r1Index: 11,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 1,
      r1Index: 13,
      r1Bid: "3h",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 7,
      maxNumC: 7,
      weight: 2,
      r1Index: 2,
      r1Bid: "1d",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 7,
      maxNumC: 7,
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 7,
      maxNumC: 7,
      weight: 2,
      r1Index: 2,
      r1Bid: "1d",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 7,
      maxNumC: 7,
      weight: 1,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 7,
      maxNumC: 7,
      weight: 2,
      r1Index: 11,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 7,
      maxNumC: 7,
      weight: 1,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 27,
      r1Bid: "6d",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 27,
      r1Bid: "6d",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 27,
      r1Bid: "6d",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 13,
      r1Bid: "3h",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 2,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 2,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 13,
      r1Bid: "3h",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 13,
      r1Bid: "3h",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: 7,
      maxNumS: 7,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 3,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: 7,
      maxNumS: 7,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: 7,
      maxNumS: 7,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 7,
      maxNumS: 7,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 7,
      maxNumS: 7,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 7,
      maxNumS: 7,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 7,
      maxNumS: 7,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 14,
      r1Bid: "3s",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 14,
      r1Bid: "3s",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 2,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      o1Index: 2,
      o1Bid: "1d",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 14,
      r1Bid: "3s",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 2,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 1,
      r1Index: 11,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 2,
      r1Index: 11,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 1,
      r1Index: 14,
      r1Bid: "3s",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 2,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 1,
      r1Index: 11,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 2,
      r1Index: 11,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 1,
      r1Index: 13,
      r1Bid: "3h",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 7,
      maxNumC: 7,
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 7,
      maxNumC: 7,
      weight: 2,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 7,
      maxNumC: 7,
      weight: 1,
      r1Index: 11,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 7,
      maxNumC: 7,
      weight: 2,
      r1Index: 11,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 7,
      maxNumC: 7,
      weight: 1,
      r1Index: 12,
      r1Bid: "3d",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: 6,
      maxNumC: 6,
      weight: 2,
      r1Index: 7,
      r1Bid: "2d",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 12,
      r1Bid: "3d",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 12,
      r1Bid: "3d",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 7,
      r1Bid: "2d",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 12,
      r1Bid: "3d",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 14,
      r1Bid: "3s",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 13,
      r1Bid: "3h",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 28,
      r1Bid: "6h",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 28,
      r1Bid: "6h",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 28,
      r1Bid: "6h",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: 7,
      maxNumS: 7,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 7,
      maxNumS: 7,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 7,
      maxNumS: 7,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 7,
      maxNumS: 7,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 7,
      maxNumS: 7,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 7,
      maxNumS: 7,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 13,
      r1Bid: "3s",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 13,
      r1Bid: "3s",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 2,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      o1Index: 3,
      o1Bid: "1h",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 13,
      r1Bid: "3s",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 1,
      r1Index: 14,
      r1Bid: "3s",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 1,
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 2,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 1,
      r1Index: 13,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 2,
      r1Index: 11,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      weight: 1,
      r1Index: 13,
      r1Bid: "3h",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 7,
      maxNumC: 7,
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 7,
      maxNumC: 7,
      weight: 2,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 7,
      maxNumC: 7,
      weight: 1,
      r1Index: 11,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 7,
      maxNumC: 7,
      weight: 2,
      r1Index: 11,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 7,
      maxNumC: 7,
      weight: 1,
      r1Index: 12,
      r1Bid: "3d",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: 6,
      maxNumC: 6,
      weight: 2,
      r1Index: 7,
      r1Bid: "2d",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 12,
      r1Bid: "3d",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 12,
      r1Bid: "3d",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 14,
      r1Bid: "3s",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 7,
      r1Bid: "2d",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 12,
      r1Bid: "3d",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 12,
      r1Bid: "3d",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 13,
      r1Bid: "3h",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 13,
      r1Bid: "3h",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 2,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 13,
      r1Bid: "3h",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 13,
      r1Bid: "3h",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 14,
      r1Bid: "3s",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: 7,
      maxNumS: 7,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 7,
      maxNumS: 7,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 7,
      maxNumS: 7,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 29,
      r1Bid: "6s",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 29,
      r1Bid: "6s",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r1",
      o1Index: 4,
      o1Bid: "1s",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 29,
      r1Bid: "6s",
    },
  ];
  var rebid_ar1_76 = ar1_76.filter(
    (itemsInArray) =>
      hand.reStrength === itemsInArray.strength &&
      (hand.numS >= itemsInArray.minNumS || itemsInArray.minNumS === "") &&
      (hand.numS <= itemsInArray.maxNumS || itemsInArray.maxNumS === "") &&
      (hand.numH >= itemsInArray.minNumH || itemsInArray.minNumH === "") &&
      (hand.numH <= itemsInArray.maxNumH || itemsInArray.maxNumH === "") &&
      (hand.numD >= itemsInArray.minNumD || itemsInArray.minNumD === "") &&
      (hand.numD <= itemsInArray.maxNumD || itemsInArray.maxNumD === "") &&
      (hand.numC >= itemsInArray.minNumC || itemsInArray.minNumC === "") &&
      (hand.numC <= itemsInArray.maxNumC || itemsInArray.maxNumC === "") &&
      o1Bid === itemsInArray.o1Bid
  );

  return rebid_ar1_76;
}
