export default function (hand, o1Bid, oc1Bid) {
  var sixCard5Card = [
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: 6,
      maxNumC: 6,
      weight: 3,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: 6,
      maxNumC: 6,
      weight: 2,
      r1Index: 2,
      r1Bid: "1d",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: 6,
      maxNumC: 6,
      weight: 2,
      r1Index: 11,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 7,
      r1Bid: "2d",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: 6,
      maxNumC: 6,
      weight: 2,
      r1Index: 12,
      r1Bid: "3d",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 2,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 2,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 11,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 2,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 3,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 2,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 2,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 11,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 3,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 5,
      maxNumC: 5,
      weight: 3,
      r1Index: 2,
      r1Bid: "1d",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 5,
      maxNumC: 5,
      weight: 2,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 5,
      maxNumC: 5,
      weight: 1,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 5,
      maxNumC: 5,
      weight: 2,
      r1Index: 2,
      r1Bid: "1d",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 5,
      maxNumC: 5,
      weight: 1,
      r1Index: 11,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 5,
      maxNumC: 5,
      weight: 2,
      r1Index: 2,
      r1Bid: "2d",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 5,
      maxNumC: 5,
      weight: 1,
      r1Index: 21,
      r1Bid: "5c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 3,
      r1Index: 2,
      r1Bid: "1d",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 3,
      r1Index: 2,
      r1Bid: "1d",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 7,
      r1Bid: "2d",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 7,
      r1Bid: "2d",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 12,
      r1Bid: "3d",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 3,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 7,
      r1Bid: "2d",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 3,
      r1Index: 2,
      r1Bid: "1d",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 7,
      r1Bid: "2d",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 2,
      r1Bid: "2d",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 4,
      r1Bid: "3d",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 5,
      maxNumS: 5,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 3,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 5,
      maxNumS: 5,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 5,
      maxNumS: 5,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 5,
      maxNumS: 5,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 3,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 5,
      maxNumS: 5,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 5,
      maxNumS: 5,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 5,
      maxNumS: 5,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 5,
      maxNumS: 5,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 13,
      r1Bid: "3h",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      weight: 3,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      weight: 3,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 13,
      r1Bid: "3h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 13,
      r1Bid: "3h",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 3,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 3,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 1,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 2,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 1,
      r1Index: 13,
      r1Bid: "3h",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 13,
      r1Bid: "3s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 13,
      r1Bid: "3s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 2,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 1,
      r1Index: 13,
      r1Bid: "3s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 5,
      maxNumC: 5,
      weight: 2,
      r1Index: 7,
      r1Bid: "2d",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 5,
      maxNumC: 5,
      weight: 1,
      r1Index: 12,
      r1Bid: "3d",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 5,
      maxNumC: 5,
      weight: 2,
      r1Index: 12,
      r1Bid: "3d",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 5,
      maxNumC: 5,
      weight: 1,
      r1Index: 17,
      r1Bid: "4d",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 5,
      maxNumC: 5,
      weight: 1,
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 3,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 7,
      r1Bid: "2d",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 12,
      r1Bid: "3d",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 12,
      r1Bid: "3d",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 17,
      r1Bid: "4d",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 7,
      r1Bid: "2d",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 12,
      r1Bid: "3d",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 12,
      r1Bid: "3d",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 17,
      r1Bid: "4d",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 5,
      maxNumS: 5,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 5,
      maxNumS: 5,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 5,
      maxNumS: 5,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 3,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 5,
      maxNumS: 5,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 5,
      maxNumS: 5,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 5,
      maxNumS: 5,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 5,
      maxNumS: 5,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 5,
      maxNumS: 5,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 2,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 1,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 3,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 2,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 1,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 2,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 1,
      r1Index: 13,
      r1Bid: "3h",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 14,
      r1Bid: "3s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      weight: 3,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 14,
      r1Bid: "3s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      weight: 3,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 14,
      r1Bid: "3s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 3,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 2,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 1,
      r1Index: 14,
      r1Bid: "3s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 3,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 2,
      r1Index: 14,
      r1Bid: "3s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 3,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 2,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 11,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 2,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 11,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 2,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 3,
      r1Index: 3,
      r1Bid: "1h",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 2,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 2,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 11,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 7,
      r1Bid: "2d",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 12,
      r1Bid: "3d",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: 6,
      maxNumC: 6,
      weight: 2,
      r1Index: 12,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 22,
      r1Bid: "5d",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 1,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 1,
      r1Index: 13,
      r1Bid: "3h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 1,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 13,
      r1Bid: "3h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 5,
      maxNumS: 5,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 5,
      maxNumS: 5,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 13,
      r1Bid: "3h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 5,
      maxNumS: 5,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 5,
      maxNumC: 5,
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 5,
      maxNumC: 5,
      weight: 1,
      r1Index: 7,
      r1Bid: "2d",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 5,
      maxNumC: 5,
      weight: 1,
      r1Index: 12,
      r1Bid: "3d",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 13,
      r1Bid: "3h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 7,
      r1Bid: "2d",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 12,
      r1Bid: "3d",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 11,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 13,
      r1Bid: "3h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 11,
      r1Bid: "3c",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 13,
      r1Bid: "3h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 18,
      r1Bid: "4h",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      weight: 2,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 14,
      r1Bid: "3s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 1,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 2,
      r1Index: 4,
      r1Bid: "1s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 2,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 1,
      r1Index: 14,
      r1Bid: "3s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 1,
      r1Index: 14,
      r1Bid: "3s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 1,
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 14,
      r1Bid: "3s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 14,
      r1Bid: "3s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 5,
      maxNumS: 5,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 5,
      maxNumS: 5,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 14,
      r1Bid: "3s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 5,
      maxNumS: 5,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: 5,
      maxNumD: 5,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 13,
      r1Bid: "3h",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 1,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 1,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: "",
      maxNumS: "",
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: "",
      minNumC: 5,
      maxNumC: 5,
      weight: 1,
      r1Index: 13,
      r1Bid: "3h",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 14,
      r1Bid: "3s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: "",
      weight: 1,
      r1Index: 12,
      r1Bid: "3d",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 5,
      maxNumC: 5,
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 5,
      maxNumC: 5,
      weight: 1,
      r1Index: 7,
      r1Bid: "2d",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 6,
      maxNumD: 6,
      minNumC: 5,
      maxNumC: 5,
      weight: 1,
      r1Index: 12,
      r1Bid: "3d",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 9,
      r1Bid: "2s",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 14,
      r1Bid: "3s",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: 5,
      maxNumS: 5,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 19,
      r1Bid: "4s",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 8,
      r1Bid: "2h",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: "",
      maxNumS: "",
      minNumH: 5,
      maxNumH: 5,
      minNumD: "",
      maxNumD: "",
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 11,
      r1Bid: "3h",
    },
    {
      bidder: "r1",
      minTP: 6,
      maxTP: 9,
      strength: "min",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 5,
      r1Bid: "1nt",
    },
    {
      bidder: "r1",
      minTP: 10,
      maxTP: 12,
      strength: "med",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 6,
      r1Bid: "2c",
    },
    {
      bidder: "r1",
      minTP: 13,
      maxTP: 19,
      strength: "max",
      o1Index: 4,
      o1Bid: "1s",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: 5,
      minNumC: 6,
      maxNumC: 6,
      weight: 1,
      r1Index: 11,
      r1Bid: "3c",
    },
  ];
  var rebidSixCard5Card = sixCard5Card.filter(
    (itemsInArray) =>
      hand.reStrength === itemsInArray.strength &&
      (hand.numS >= itemsInArray.minNumS || itemsInArray.minNumS === "") &&
      (hand.numS <= itemsInArray.maxNumS || itemsInArray.maxNumS === "") &&
      (hand.numH >= itemsInArray.minNumH || itemsInArray.minNumH === "") &&
      (hand.numH <= itemsInArray.maxNumH || itemsInArray.maxNumH === "") &&
      (hand.numD >= itemsInArray.minNumD || itemsInArray.minNumD === "") &&
      (hand.numD <= itemsInArray.maxNumD || itemsInArray.maxNumD === "") &&
      (hand.numC >= itemsInArray.minNumC || itemsInArray.minNumC === "") &&
      (hand.numC <= itemsInArray.maxNumC || itemsInArray.maxNumC === "") &&
      o1Bid === itemsInArray.o1Bid
  );
  return rebidSixCard5Card;
}
