function get_ao1_74(hand) {
  var ao1_74 = [
    {
      bidder: "oc1",
      weight: 1,
      minTP: 8,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: 7,
      maxNumC: 7,
      oc1Index: 1,
      oc1Bid: "2c",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 8,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      oc1Index: 1,
      oc1Bid: "2c",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 8,
      maxTP: 9,
      strength: "min",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      oc1Index: 1,
      oc1Bid: "2c",
    },
    {
      bidder: "oc1",
      weight: 2,
      minTP: 8,
      maxTP: 9,
      strength: "min",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      oc1Index: 1,
      oc1Bid: "2c",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: 7,
      maxNumC: 7,
      oc1Index: 6,
      oc1Bid: "2c",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      oc1Index: 6,
      oc1Bid: "2c",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      oc1Index: 6,
      oc1Bid: "2c",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: 7,
      maxNumC: 7,
      oc1Index: 11,
      oc1Bid: "3c",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      oc1Index: 11,
      oc1Bid: "3c",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 7,
      maxNumC: 7,
      oc1Index: 11,
      oc1Bid: "3c",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 8,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: 4,
      maxNumC: 4,
      oc1Index: 2,
      oc1Bid: "1d",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 8,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      oc1Index: 2,
      oc1Bid: "1d",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 8,
      maxTP: 9,
      strength: "min",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      oc1Index: 2,
      oc1Bid: "1d",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: 4,
      maxNumC: 4,
      oc1Index: 7,
      oc1Bid: "2d",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      oc1Index: 7,
      oc1Bid: "2d",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      oc1Index: 7,
      oc1Bid: "2d",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: 4,
      maxNumC: 4,
      oc1Index: 12,
      oc1Bid: "3d",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 4,
      maxNumH: 4,
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      oc1Index: 12,
      oc1Bid: "3d",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: "",
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: "",
      oc1Index: 12,
      oc1Bid: "3d",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 8,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      oc1Index: 3,
      oc1Bid: "1h",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 8,
      maxTP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      oc1Index: 3,
      oc1Bid: "1h",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 8,
      maxTP: 9,
      strength: "min",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      oc1Index: 3,
      oc1Bid: "1h",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      oc1Index: 8,
      oc1Bid: "2h",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      oc1Index: 8,
      oc1Bid: "2h",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      oc1Index: 8,
      oc1Bid: "2h",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      oc1Index: 13,
      oc1Bid: "3h",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: "",
      minNumH: 7,
      maxNumH: 7,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      oc1Index: 13,
      oc1Bid: "3h",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      oc1Index: 13,
      oc1Bid: "3h",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 8,
      maxTP: 9,
      strength: "min",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      oc1Index: 4,
      oc1Bid: "1s",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 8,
      maxTP: 9,
      strength: "min",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      oc1Index: 4,
      oc1Bid: "1s",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 8,
      maxTP: 9,
      strength: "min",
      minNumS: 7,
      maxNumS: 7,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      oc1Index: 4,
      oc1Bid: "1s",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      oc1Index: 8,
      oc1Bid: "2s",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      oc1Index: 8,
      oc1Bid: "2s",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 10,
      maxTP: 12,
      strength: "med",
      minNumS: 7,
      maxNumS: 7,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      oc1Index: 8,
      oc1Bid: "2s",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 4,
      maxNumC: 4,
      oc1Index: 14,
      oc1Bid: "3s",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: "",
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: "",
      oc1Index: 14,
      oc1Bid: "3s",
    },
    {
      bidder: "oc1",
      weight: 1,
      minTP: 13,
      maxTP: 19,
      strength: "max",
      minNumS: 7,
      maxNumS: 7,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      oc1Index: 14,
      oc1Bid: "3s",
    },
  ];
  var rebid_ao1_74 = ao1_74.filter(
    (itemsInArray) =>
      hand.ocStrength === itemsInArray.strength &&
      (hand.numS >= itemsInArray.minNumS || itemsInArray.minNumS === "") &&
      (hand.numS <= itemsInArray.maxNumS || itemsInArray.maxNumS === "") &&
      (hand.numH >= itemsInArray.minNumH || itemsInArray.minNumH === "") &&
      (hand.numH <= itemsInArray.maxNumH || itemsInArray.maxNumH === "") &&
      (hand.numD >= itemsInArray.minNumD || itemsInArray.minNumD === "") &&
      (hand.numD <= itemsInArray.maxNumD || itemsInArray.maxNumD === "") &&
      (hand.numC >= itemsInArray.minNumC || itemsInArray.minNumC === "") &&
      (hand.numC <= itemsInArray.maxNumC || itemsInArray.maxNumC === "")
  );
  return rebid_ao1_74;
}
