export default function (hand) {
  var oc1_unusual2NT = [
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 8,
      maxHCP: 9,
      o1Index: 3,
      o1Bid: "1h",
      strength: "art",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 5,
      maxNumD: 5,
      minNumC: 5,
      maxNumC: 5,
      forcingBid: "TRUE",
      ocIndex: 10,
      ocBid: "2nt",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 8,
      maxHCP: 9,
      o1Index: 4,
      o1Bid: "1s",
      strength: "art",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 5,
      maxNumD: 5,
      minNumC: 5,
      maxNumC: 5,
      forcingBid: "TRUE",
      ocIndex: 10,
      ocBid: "2nt",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 10,
      maxHCP: 16,
      o1Index: 3,
      o1Bid: "1h",
      strength: "art",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 5,
      maxNumD: 5,
      minNumC: 5,
      maxNumC: 5,
      forcingBid: "TRUE",
      ocIndex: 10,
      ocBid: "2nt",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 10,
      maxHCP: 16,
      o1Index: 4,
      o1Bid: "1s",
      strength: "art",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 5,
      maxNumD: 5,
      minNumC: 5,
      maxNumC: 5,
      forcingBid: "TRUE",
      ocIndex: 10,
      ocBid: "2nt",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 17,
      maxHCP: 19,
      o1Index: 3,
      o1Bid: "1h",
      strength: "art",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 5,
      maxNumD: 5,
      minNumC: 5,
      maxNumC: 5,
      forcingBid: "TRUE",
      ocIndex: 10,
      ocBid: "2nt",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 17,
      maxHCP: 19,
      o1Index: 4,
      o1Bid: "1s",
      strength: "art",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 5,
      maxNumD: 5,
      minNumC: 5,
      maxNumC: 5,
      forcingBid: "TRUE",
      ocIndex: 10,
      ocBid: "2nt",
    },
  ];
  var rebid_aoc1_unusual2NT = oc1_unusual2NT.filter(
    (itemsInArray) =>
      hand.ocStrength === itemsInArray.strength &&
      (hand.numS >= itemsInArray.minNumS || itemsInArray.minNumS === "") &&
      (hand.numS <= itemsInArray.maxNumS || itemsInArray.maxNumS === "") &&
      (hand.numH >= itemsInArray.minNumH || itemsInArray.minNumH === "") &&
      (hand.numH <= itemsInArray.maxNumH || itemsInArray.maxNumH === "") &&
      (hand.numD >= itemsInArray.minNumD || itemsInArray.minNumD === "") &&
      (hand.numD <= itemsInArray.maxNumD || itemsInArray.maxNumD === "") &&
      (hand.numC >= itemsInArray.minNumC || itemsInArray.minNumC === "") &&
      (hand.numC <= itemsInArray.maxNumC || itemsInArray.maxNumC === "")
  );
  return rebid_aoc1_unusual2NT;
}
