// overcaller 1
export default function (hand) {
  var aoc1_7 = [
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 8,
      maxHCP: 9,
      strength: "art",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      ocIndex: 4,
      oc1Bid: "3s",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 10,
      maxHCP: 12,
      strength: "art",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      ocIndex: 4,
      oc1Bid: "3s",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 13,
      maxHCP: 19,
      strength: "art",
      minNumS: 7,
      maxNumS: 7,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      ocIndex: 4,
      oc1Bid: "3s",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 8,
      maxHCP: 9,
      strength: "art",
      minNumS: "",
      maxNumS: 3,
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      ocIndex: 3,
      oc1Bid: "3h",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 10,
      maxHCP: 12,
      strength: "art",
      minNumS: "",
      maxNumS: 3,
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      ocIndex: 3,
      oc1Bid: "3h",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 13,
      maxHCP: 19,
      strength: "art",
      minNumS: "",
      maxNumS: 3,
      minNumH: 7,
      maxNumH: 7,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      ocIndex: 3,
      oc1Bid: "3h",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 8,
      maxHCP: 9,
      strength: "art",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: 3,
      ocIndex: 2,
      oc1Bid: "3d",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 10,
      maxHCP: 12,
      strength: "art",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: 3,
      ocIndex: 2,
      oc1Bid: "3d",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 13,
      maxHCP: 19,
      strength: "art",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 7,
      maxNumD: 7,
      minNumC: "",
      maxNumC: 3,
      ocIndex: 2,
      oc1Bid: "3d",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 8,
      maxHCP: 9,
      strength: "art",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 7,
      maxNumC: 7,
      ocIndex: 1,
      oc1Bid: "3c",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 10,
      maxHCP: 12,
      strength: "art",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 7,
      maxNumC: 7,
      ocIndex: 1,
      oc1Bid: "3c",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 13,
      maxHCP: 19,
      strength: "art",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 7,
      maxNumC: 7,
      ocIndex: 1,
      oc1Bid: "3c",
    },
  ];
  var rebid_aoc1_7 = aoc1_7.filter(
    (itemsInArray) =>
      hand.ocStrength === itemsInArray.strength &&
      (hand.numS >= itemsInArray.minNumS || itemsInArray.minNumS === "") &&
      (hand.numS <= itemsInArray.maxNumS || itemsInArray.maxNumS === "") &&
      (hand.numH >= itemsInArray.minNumH || itemsInArray.minNumH === "") &&
      (hand.numH <= itemsInArray.maxNumH || itemsInArray.maxNumH === "") &&
      (hand.numD >= itemsInArray.minNumD || itemsInArray.minNumD === "") &&
      (hand.numD <= itemsInArray.maxNumD || itemsInArray.maxNumD === "") &&
      (hand.numC >= itemsInArray.minNumC || itemsInArray.minNumC === "") &&
      (hand.numC <= itemsInArray.maxNumC || itemsInArray.maxNumC === "")
  );
  return rebid_aoc1_7;
}
