export default function (hand) {
  var oc1_oneLongSuit = [
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 8,
      maxHCP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 5,
      maxNumC: "",
      ocIndex: 6,
      oc1Bid: "2c",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 10,
      maxHCP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 5,
      maxNumC: "",
      ocIndex: 6,
      oc1Bid: "2c",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 17,
      maxHCP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 5,
      maxNumC: "",
      ocIndex: 6,
      oc1Bid: "2c",
    },
    {
      bidder: "oc1",
      weight: 2,
      minHCP: 8,
      maxHCP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 5,
      maxNumD: "",
      minNumC: "",
      maxNumC: 4,
      ocIndex: 2,
      oc1Bid: "1d",
    },
    {
      bidder: "oc1",
      weight: 2,
      minHCP: 10,
      maxHCP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 5,
      maxNumD: "",
      minNumC: "",
      maxNumC: 4,
      ocIndex: 2,
      oc1Bid: "1d",
    },
    {
      bidder: "oc1",
      weight: 2,
      minHCP: 17,
      maxHCP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 5,
      maxNumD: "",
      minNumC: "",
      maxNumC: 4,
      ocIndex: 2,
      oc1Bid: "1d",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 10,
      maxHCP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 5,
      maxNumD: "",
      minNumC: "",
      maxNumC: 4,
      ocIndex: 7,
      oc1Bid: "2d",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 17,
      maxHCP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 5,
      maxNumD: "",
      minNumC: "",
      maxNumC: 4,
      ocIndex: 7,
      oc1Bid: "2d",
    },
    {
      bidder: "oc1",
      weight: 2,
      minHCP: 8,
      maxHCP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: 3,
      minNumH: 5,
      maxNumH: "",
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 4,
      ocIndex: 3,
      oc1Bid: "1h",
    },
    {
      bidder: "oc1",
      weight: 2,
      minHCP: 10,
      maxHCP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: 3,
      minNumH: 5,
      maxNumH: "",
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 4,
      ocIndex: 3,
      oc1Bid: "1h",
    },
    {
      bidder: "oc1",
      weight: 2,
      minHCP: 17,
      maxHCP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: 3,
      minNumH: 5,
      maxNumH: "",
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 4,
      ocIndex: 3,
      oc1Bid: "1h",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 10,
      maxHCP: 16,
      strength: "med",
      minNumS: "",
      maxNumS: 3,
      minNumH: 5,
      maxNumH: "",
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 4,
      ocIndex: 8,
      oc1Bid: "2h",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 17,
      maxHCP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: 3,
      minNumH: 5,
      maxNumH: "",
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 4,
      ocIndex: 8,
      oc1Bid: "2h",
    },
    {
      bidder: "oc1",
      weight: 2,
      minHCP: 8,
      maxHCP: 9,
      strength: "min",
      minNumS: 5,
      maxNumS: "",
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 4,
      ocIndex: 4,
      oc1Bid: "1s",
    },
    {
      bidder: "oc1",
      weight: 2,
      minHCP: 10,
      maxHCP: 16,
      strength: "med",
      minNumS: 5,
      maxNumS: "",
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 4,
      ocIndex: 4,
      oc1Bid: "1s",
    },
    {
      bidder: "oc1",
      weight: 2,
      minHCP: 17,
      maxHCP: 19,
      strength: "max",
      minNumS: 5,
      maxNumS: "",
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 4,
      ocIndex: 4,
      oc1Bid: "1s",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 10,
      maxHCP: 16,
      strength: "med",
      minNumS: 5,
      maxNumS: "",
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 4,
      ocIndex: 9,
      oc1Bid: "2s",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 17,
      maxHCP: 19,
      strength: "max",
      minNumS: 5,
      maxNumS: "",
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 4,
      ocIndex: 9,
      oc1Bid: "2s",
    },
  ];
  var rebid_aoc1_oneLongSuit = oc1_oneLongSuit.filter(
    (itemsInArray) =>
      hand.ocStrength === itemsInArray.strength &&
      (hand.numS >= itemsInArray.minNumS || itemsInArray.minNumS === "") &&
      (hand.numS <= itemsInArray.maxNumS || itemsInArray.maxNumS === "") &&
      (hand.numH >= itemsInArray.minNumH || itemsInArray.minNumH === "") &&
      (hand.numH <= itemsInArray.maxNumH || itemsInArray.maxNumH === "") &&
      (hand.numD >= itemsInArray.minNumD || itemsInArray.minNumD === "") &&
      (hand.numD <= itemsInArray.maxNumD || itemsInArray.maxNumD === "") &&
      (hand.numC >= itemsInArray.minNumC || itemsInArray.minNumC === "") &&
      (hand.numC <= itemsInArray.maxNumC || itemsInArray.maxNumC === "")
  );
  return rebid_aoc1_oneLongSuit;
}
