function get_aoc1_66(hand) {
  var oc1_66 = [
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 8,
      maxHCP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 6,
      maxNumD: 6,
      minNumC: 6,
      maxNumC: 6,
      oc1Index: 2,
      ocBid: "1d",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 10,
      maxHCP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 6,
      maxNumD: 6,
      minNumC: 6,
      maxNumC: 6,
      oc1Index: 2,
      ocBid: "1d",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 13,
      maxHCP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 6,
      maxNumD: 6,
      minNumC: 6,
      maxNumC: 6,
      oc1Index: 2,
      ocBid: "1d",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 8,
      maxHCP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: 3,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: 3,
      minNumC: 6,
      maxNumC: 6,
      oc1Index: 3,
      ocBid: "1h",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 10,
      maxHCP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: 3,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: 3,
      minNumC: 6,
      maxNumC: 6,
      oc1Index: 3,
      ocBid: "1h",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 13,
      maxHCP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: 3,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: 3,
      minNumC: 6,
      maxNumC: 6,
      oc1Index: 3,
      ocBid: "1h",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 8,
      maxHCP: 9,
      strength: "min",
      minNumS: "",
      maxNumS: 3,
      minNumH: 6,
      maxNumH: 6,
      minNumD: 6,
      maxNumD: "",
      minNumC: "",
      maxNumC: 3,
      oc1Index: 3,
      ocBid: "1h",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 10,
      maxHCP: 12,
      strength: "med",
      minNumS: "",
      maxNumS: 3,
      minNumH: 6,
      maxNumH: 6,
      minNumD: 6,
      maxNumD: "",
      minNumC: "",
      maxNumC: 3,
      oc1Index: 3,
      ocBid: "1h",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 13,
      maxHCP: 19,
      strength: "max",
      minNumS: "",
      maxNumS: 3,
      minNumH: 6,
      maxNumH: 6,
      minNumD: 6,
      maxNumD: "",
      minNumC: "",
      maxNumC: 3,
      oc1Index: 3,
      ocBid: "1h",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 8,
      maxHCP: 9,
      strength: "min",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 6,
      maxNumC: 6,
      oc1Index: 4,
      ocBid: "1s",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 10,
      maxHCP: 12,
      strength: "med",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 6,
      maxNumC: 6,
      oc1Index: 4,
      ocBid: "1s",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 13,
      maxHCP: 19,
      strength: "max",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 6,
      maxNumC: 6,
      oc1Index: 4,
      ocBid: "1s",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 8,
      maxHCP: 9,
      strength: "min",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: 3,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: 3,
      oc1Index: 4,
      ocBid: "1s",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 10,
      maxHCP: 12,
      strength: "med",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: 3,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: 3,
      oc1Index: 4,
      ocBid: "1s",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 13,
      maxHCP: 19,
      strength: "max",
      minNumS: 6,
      maxNumS: 6,
      minNumH: "",
      maxNumH: 3,
      minNumD: 6,
      maxNumD: 6,
      minNumC: "",
      maxNumC: 3,
      oc1Index: 4,
      ocBid: "1s",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 8,
      maxHCP: 9,
      strength: "min",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      oc1Index: 4,
      ocBid: "1s",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 10,
      maxHCP: 12,
      strength: "med",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      oc1Index: 4,
      ocBid: "1s",
    },
    {
      bidder: "oc1",
      weight: 1,
      minHCP: 13,
      maxHCP: 19,
      strength: "max",
      minNumS: 6,
      maxNumS: 6,
      minNumH: 6,
      maxNumH: 6,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      oc1Index: 4,
      ocBid: "1s",
    },
  ];
  var rebid_aoc1_66 = oc1_66.filter(
    (itemsInArray) =>
      hand.ocStrength === itemsInArray.strength &&
      (hand.numS >= itemsInArray.minNumS || itemsInArray.minNumS === "") &&
      (hand.numS <= itemsInArray.maxNumS || itemsInArray.maxNumS === "") &&
      (hand.numH >= itemsInArray.minNumH || itemsInArray.minNumH === "") &&
      (hand.numH <= itemsInArray.maxNumH || itemsInArray.maxNumH === "") &&
      (hand.numD >= itemsInArray.minNumD || itemsInArray.minNumD === "") &&
      (hand.numD <= itemsInArray.maxNumD || itemsInArray.maxNumD === "") &&
      (hand.numC >= itemsInArray.minNumC || itemsInArray.minNumC === "") &&
      (hand.numC <= itemsInArray.maxNumC || itemsInArray.maxNumC === "")
  );
  return rebid_aoc1_66;
}
