export default function (hand, o1Bid, r1Bid, o2Bid, r2Bid) {
  var fourCard4Card4Card = [
    {
      bidder: "o3",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 9,
      r2Bid: "2s",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 13,
      o3Bid: "3h",
    },
    {
      bidder: "o3",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 10,
      r2Bid: "2nt",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 11,
      r2Bid: "3c",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 13,
      o3Bid: "3h",
    },
    {
      bidder: "o3",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 12,
      r2Bid: "3d",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 13,
      o3Bid: "3h",
    },
    {
      bidder: "o3",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 13,
      r2Bid: "3h",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 14,
      r2Bid: "3s",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 15,
      r2Bid: "3nt",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 16,
      r2Bid: "4c",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 17,
      r2Bid: "4d",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 18,
      r2Bid: "4h",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 19,
      r2Bid: "4s",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 23,
      o3Bid: "5h",
    },
    {
      bidder: "o3",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 21,
      r2Bid: "5c",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 23,
      o3Bid: "5h",
    },
    {
      bidder: "o3",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 22,
      r2Bid: "5d",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 23,
      o3Bid: "5h",
    },
    {
      bidder: "o3",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 6,
      o2Bid: "2c",
      r2Index: 7,
      r2Bid: "2d",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 10,
      o3Bid: "2nt",
    },
    {
      bidder: "o3",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 6,
      o2Bid: "2c",
      r2Index: 8,
      r2Bid: "2h",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 13,
      o3Bid: "3h",
    },
    {
      bidder: "o3",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 6,
      o2Bid: "2c",
      r2Index: 9,
      r2Bid: "2s",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 10,
      o3Bid: "2nt",
    },
    {
      bidder: "o3",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 6,
      o2Bid: "2c",
      r2Index: 13,
      r2Bid: "3h",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 6,
      o2Bid: "2c",
      r2Index: 14,
      r2Bid: "3s",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 9,
      r2Bid: "2s",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 13,
      o3Bid: "3h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 10,
      r2Bid: "2nt",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 11,
      r2Bid: "3c",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 12,
      r2Bid: "3d",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 13,
      r2Bid: "3h",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 14,
      r2Bid: "3s",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 15,
      r2Bid: "3nt",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 16,
      r2Bid: "4c",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 17,
      r2Bid: "4d",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 18,
      r2Bid: "4h",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 19,
      r2Bid: "4s",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 23,
      o3Bid: "5h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 21,
      r2Bid: "5c",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 23,
      o3Bid: "5h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 22,
      r2Bid: "5d",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 23,
      o3Bid: "5h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 6,
      o2Bid: "2c",
      r2Index: 7,
      r2Bid: "2d",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 6,
      o2Bid: "2c",
      r2Index: 8,
      r2Bid: "2h",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 6,
      o2Bid: "2c",
      r2Index: 9,
      r2Bid: "2s",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 10,
      o3Bid: "2nt",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 6,
      o2Bid: "2c",
      r2Index: 10,
      r2Bid: "2nt",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 6,
      o2Bid: "2c",
      r2Index: 11,
      r2Bid: "3c",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 16,
      o3Bid: "4c",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 6,
      o2Bid: "2c",
      r2Index: 12,
      r2Bid: "3d",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 22,
      o3Bid: "5d",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 6,
      o2Bid: "2c",
      r2Index: 13,
      r2Bid: "3h",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 6,
      o2Bid: "2c",
      r2Index: 14,
      r2Bid: "3s",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 6,
      o2Bid: "2c",
      r2Index: 15,
      r2Bid: "3nt",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 6,
      o2Bid: "2c",
      r2Index: 16,
      r2Bid: "4c",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 21,
      o3Bid: "5c",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 6,
      o2Bid: "2c",
      r2Index: 17,
      r2Bid: "4d",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 22,
      o3Bid: "5d",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 6,
      o2Bid: "2c",
      r2Index: 18,
      r2Bid: "4h",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 6,
      o2Bid: "2c",
      r2Index: 19,
      r2Bid: "4s",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 6,
      o2Bid: "2c",
      r2Index: 21,
      r2Bid: "5c",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 6,
      o2Bid: "2c",
      r2Index: 22,
      r2Bid: "5d",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 8,
      r1Bid: "2h",
      o2Index: 13,
      o2Bid: "3h",
      r2Index: 14,
      r2Bid: "3s",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 8,
      r1Bid: "2h",
      o2Index: 13,
      o2Bid: "3h",
      r2Index: 15,
      r2Bid: "3nt",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 8,
      r1Bid: "2h",
      o2Index: 13,
      o2Bid: "3h",
      r2Index: 16,
      r2Bid: "4c",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 8,
      r1Bid: "2h",
      o2Index: 13,
      o2Bid: "3h",
      r2Index: 17,
      r2Bid: "4d",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 8,
      r1Bid: "2h",
      o2Index: 13,
      o2Bid: "3h",
      r2Index: 18,
      r2Bid: "4h",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 8,
      r1Bid: "2h",
      o2Index: 13,
      o2Bid: "3h",
      r2Index: 19,
      r2Bid: "4s",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 8,
      r1Bid: "2h",
      o2Index: 13,
      o2Bid: "3h",
      r2Index: 21,
      r2Bid: "5c",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 23,
      o3Bid: "5h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 8,
      r1Bid: "2h",
      o2Index: 13,
      o2Bid: "3h",
      r2Index: 22,
      r2Bid: "5d",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 23,
      o3Bid: "5h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 9,
      r1Bid: "2s",
      o2Index: 10,
      o2Bid: "2nt",
      r2Index: 11,
      r2Bid: "3c",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 9,
      r1Bid: "2s",
      o2Index: 10,
      o2Bid: "2nt",
      r2Index: 12,
      r2Bid: "3d",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 9,
      r1Bid: "2s",
      o2Index: 10,
      o2Bid: "2nt",
      r2Index: 13,
      r2Bid: "3h",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 9,
      r1Bid: "2s",
      o2Index: 10,
      o2Bid: "2nt",
      r2Index: 14,
      r2Bid: "3s",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 18,
      o2Bid: "3h",
      r2Index: 14,
      r2Bid: "3s",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 18,
      o2Bid: "3h",
      r2Index: 15,
      r2Bid: "3nt",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 18,
      o2Bid: "3h",
      r2Index: 16,
      r2Bid: "4c",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 18,
      o2Bid: "3h",
      r2Index: 17,
      r2Bid: "4d",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 18,
      o2Bid: "3h",
      r2Index: 18,
      r2Bid: "4h",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 18,
      o2Bid: "3h",
      r2Index: 19,
      r2Bid: "4s",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 18,
      o2Bid: "3h",
      r2Index: 21,
      r2Bid: "5c",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 23,
      o3Bid: "5h",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 18,
      o2Bid: "3h",
      r2Index: 22,
      r2Bid: "5d",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o3Index: 23,
      o3Bid: "5h",
    },
    {
      bidder: "o3",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 4,
      o2Bid: "1s",
      r2Index: 11,
      r2Bid: "3c",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 4,
      o2Bid: "1s",
      r2Index: 12,
      r2Bid: "3d",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 4,
      o2Bid: "1s",
      r2Index: 13,
      r2Bid: "3h",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 10,
      r2Bid: "2nt",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 14,
      o3Bid: "3s",
    },
    {
      bidder: "o3",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 11,
      r2Bid: "3c",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 14,
      o3Bid: "3s",
    },
    {
      bidder: "o3",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 12,
      r2Bid: "3d",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 14,
      o3Bid: "3s",
    },
    {
      bidder: "o3",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 13,
      r2Bid: "3h",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 14,
      o3Bid: "3s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 4,
      o2Bid: "1s",
      r2Index: 6,
      r2Bid: "2c",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 4,
      o2Bid: "1s",
      r2Index: 7,
      r2Bid: "2d",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 4,
      o2Bid: "1s",
      r2Index: 8,
      r2Bid: "2h",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 4,
      o2Bid: "1s",
      r2Index: 9,
      r2Bid: "2s",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 14,
      o3Bid: "3s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 4,
      o2Bid: "1s",
      r2Index: 10,
      r2Bid: "2nt",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 4,
      o2Bid: "1s",
      r2Index: 11,
      r2Bid: "3c",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 4,
      o2Bid: "1s",
      r2Index: 12,
      r2Bid: "3d",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 4,
      o2Bid: "1s",
      r2Index: 13,
      r2Bid: "3h",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 4,
      o2Bid: "1s",
      r2Index: 14,
      r2Bid: "3s",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 15,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 4,
      o2Bid: "1s",
      r2Index: 15,
      r2Bid: "3nt",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 4,
      o2Bid: "1s",
      r2Index: 16,
      r2Bid: "4c",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 4,
      o2Bid: "1s",
      r2Index: 17,
      r2Bid: "4d",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 4,
      o2Bid: "1s",
      r2Index: 18,
      r2Bid: "4h",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 4,
      o2Bid: "1s",
      r2Index: 19,
      r2Bid: "4s",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 4,
      o2Bid: "1s",
      r2Index: 21,
      r2Bid: "5c",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 4,
      o2Bid: "1s",
      r2Index: 22,
      r2Bid: "5d",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 10,
      r2Bid: "2nt",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 18,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 11,
      r2Bid: "3c",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 18,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 12,
      r2Bid: "3d",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 18,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 13,
      r2Bid: "3h",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 18,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 14,
      r2Bid: "3s",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 18,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 15,
      r2Bid: "3nt",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 18,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 16,
      r2Bid: "4c",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 18,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 17,
      r2Bid: "4d",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 18,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 18,
      r2Bid: "4h",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 18,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 11,
      o2Bid: "3c",
      r2Index: 12,
      r2Bid: "3d",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 11,
      o2Bid: "3c",
      r2Index: 13,
      r2Bid: "3h",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 11,
      o2Bid: "3c",
      r2Index: 14,
      r2Bid: "3s",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 18,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 11,
      o2Bid: "3c",
      r2Index: 15,
      r2Bid: "3nt",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 11,
      o2Bid: "3c",
      r2Index: 16,
      r2Bid: "4c",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 21,
      o3Bid: "5c",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 11,
      o2Bid: "3c",
      r2Index: 17,
      r2Bid: "4d",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 22,
      o3Bid: "5d",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 11,
      o2Bid: "3c",
      r2Index: 18,
      r2Bid: "4h",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 21,
      o3Bid: "5c",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 11,
      o2Bid: "3c",
      r2Index: 19,
      r2Bid: "4s",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 11,
      o2Bid: "3c",
      r2Index: 21,
      r2Bid: "5c",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 11,
      o2Bid: "3c",
      r2Index: 22,
      r2Bid: "5d",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 7,
      r1Bid: "2d",
      o2Index: 12,
      o2Bid: "3d",
      r2Index: 13,
      r2Bid: "3h",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 7,
      r1Bid: "2d",
      o2Index: 12,
      o2Bid: "3d",
      r2Index: 14,
      r2Bid: "3s",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 7,
      r1Bid: "2d",
      o2Index: 12,
      o2Bid: "3d",
      r2Index: 15,
      r2Bid: "3nt",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 7,
      r1Bid: "2d",
      o2Index: 12,
      o2Bid: "3d",
      r2Index: 16,
      r2Bid: "4c",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 21,
      o3Bid: "5c",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 7,
      r1Bid: "2d",
      o2Index: 12,
      o2Bid: "3d",
      r2Index: 17,
      r2Bid: "4d",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 22,
      o3Bid: "5d",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 8,
      r1Bid: "2h",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 10,
      r2Bid: "2nt",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 8,
      r1Bid: "2h",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 11,
      r2Bid: "3c",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 8,
      r1Bid: "2h",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 12,
      r2Bid: "3d",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 8,
      r1Bid: "2h",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 13,
      r2Bid: "3h",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 8,
      r1Bid: "2h",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 14,
      r2Bid: "3s",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 8,
      r1Bid: "2h",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 15,
      r2Bid: "3nt",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 8,
      r1Bid: "2h",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 16,
      r2Bid: "4c",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 21,
      o3Bid: "5c",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 8,
      r1Bid: "2h",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 17,
      r2Bid: "4d",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 22,
      o3Bid: "5d",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 9,
      r1Bid: "2s",
      o2Index: 11,
      o2Bid: "3c",
      r2Index: 12,
      r2Bid: "3d",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 9,
      r1Bid: "2s",
      o2Index: 11,
      o2Bid: "3c",
      r2Index: 13,
      r2Bid: "3h",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 9,
      r1Bid: "2s",
      o2Index: 11,
      o2Bid: "3c",
      r2Index: 14,
      r2Bid: "3s",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 9,
      r1Bid: "2s",
      o2Index: 11,
      o2Bid: "3c",
      r2Index: 15,
      r2Bid: "3nt",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 9,
      r1Bid: "2s",
      o2Index: 11,
      o2Bid: "3c",
      r2Index: 16,
      r2Bid: "4c",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 9,
      r1Bid: "2s",
      o2Index: 11,
      o2Bid: "3c",
      r2Index: 17,
      r2Bid: "4d",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 4,
      o2Bid: "1s",
      r2Index: 5,
      r2Bid: "1nt",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 10,
      o3Bid: "2nt",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 4,
      o2Bid: "1s",
      r2Index: 6,
      r2Bid: "2c",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 4,
      o2Bid: "1s",
      r2Index: 7,
      r2Bid: "2d",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 4,
      o2Bid: "1s",
      r2Index: 8,
      r2Bid: "2h",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 4,
      o2Bid: "1s",
      r2Index: 9,
      r2Bid: "2s",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 4,
      o2Bid: "1s",
      r2Index: 10,
      r2Bid: "2nt",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 4,
      o2Bid: "1s",
      r2Index: 11,
      r2Bid: "3c",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 4,
      o2Bid: "1s",
      r2Index: 12,
      r2Bid: "3d",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 4,
      o2Bid: "1s",
      r2Index: 13,
      r2Bid: "3h",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 4,
      o2Bid: "1s",
      r2Index: 14,
      r2Bid: "3s",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 4,
      o2Bid: "1s",
      r2Index: 15,
      r2Bid: "3nt",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 10,
      r2Bid: "2nt",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 11,
      r2Bid: "3c",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 12,
      r2Bid: "3d",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 13,
      r2Bid: "3h",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 14,
      r2Bid: "3s",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 15,
      r2Bid: "3nt",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 16,
      r2Bid: "4c",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 17,
      r2Bid: "4d",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 18,
      r2Bid: "4h",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 19,
      r2Bid: "4s",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 11,
      o2Bid: "3c",
      r2Index: 12,
      r2Bid: "3d",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 11,
      o2Bid: "3c",
      r2Index: 13,
      r2Bid: "3h",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 11,
      o2Bid: "3c",
      r2Index: 14,
      r2Bid: "3s",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 11,
      o2Bid: "3c",
      r2Index: 15,
      r2Bid: "3nt",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 11,
      o2Bid: "3c",
      r2Index: 16,
      r2Bid: "4c",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 21,
      o3Bid: "5c",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 11,
      o2Bid: "3c",
      r2Index: 17,
      r2Bid: "4d",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 22,
      o3Bid: "5d",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 11,
      o2Bid: "3c",
      r2Index: 18,
      r2Bid: "4h",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 21,
      o3Bid: "5c",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 11,
      o2Bid: "3c",
      r2Index: 19,
      r2Bid: "4s",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 11,
      o2Bid: "3c",
      r2Index: 21,
      r2Bid: "5c",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 11,
      o2Bid: "3c",
      r2Index: 22,
      r2Bid: "5d",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 8,
      r1Bid: "2h",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 10,
      r2Bid: "2nt",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 8,
      r1Bid: "2h",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 11,
      r2Bid: "3c",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 8,
      r1Bid: "2h",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 12,
      r2Bid: "3d",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 8,
      r1Bid: "2h",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 13,
      r2Bid: "3h",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 8,
      r1Bid: "2h",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 14,
      r2Bid: "3s",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 8,
      r1Bid: "2h",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 15,
      r2Bid: "3nt",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 8,
      r1Bid: "2h",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 16,
      r2Bid: "4c",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 21,
      o3Bid: "5c",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 8,
      r1Bid: "2h",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 17,
      r2Bid: "4d",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 22,
      o3Bid: "5d",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 9,
      r1Bid: "2s",
      o2Index: 11,
      o2Bid: "3c",
      r2Index: 12,
      r2Bid: "3d",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 9,
      r1Bid: "2s",
      o2Index: 11,
      o2Bid: "3c",
      r2Index: 13,
      r2Bid: "3h",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 9,
      r1Bid: "2s",
      o2Index: 11,
      o2Bid: "3c",
      r2Index: 14,
      r2Bid: "3s",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 9,
      r1Bid: "2s",
      o2Index: 11,
      o2Bid: "3c",
      r2Index: 15,
      r2Bid: "3nt",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 9,
      r1Bid: "2s",
      o2Index: 11,
      o2Bid: "3c",
      r2Index: 16,
      r2Bid: "4c",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 9,
      r1Bid: "2s",
      o2Index: 11,
      o2Bid: "3c",
      r2Index: 17,
      r2Bid: "4d",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 9,
      r1Bid: "2s",
      o2Index: 11,
      o2Bid: "3c",
      r2Index: 18,
      r2Bid: "4h",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 2,
      r1Bid: "1d",
      o2Index: 3,
      o2Bid: "1h",
      r2Index: 4,
      r2Bid: "1s",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 14,
      o3Bid: "3s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 2,
      r1Bid: "1d",
      o2Index: 3,
      o2Bid: "1h",
      r2Index: 5,
      r2Bid: "1nt",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 2,
      r1Bid: "1d",
      o2Index: 3,
      o2Bid: "1h",
      r2Index: 6,
      r2Bid: "2c",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 11,
      o3Bid: "3c",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 2,
      r1Bid: "1d",
      o2Index: 3,
      o2Bid: "1h",
      r2Index: 7,
      r2Bid: "2d",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 10,
      o3Bid: "2nt",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 2,
      r1Bid: "1d",
      o2Index: 3,
      o2Bid: "1h",
      r2Index: 8,
      r2Bid: "2h",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 2,
      r1Bid: "1d",
      o2Index: 3,
      o2Bid: "1h",
      r2Index: 9,
      r2Bid: "2s",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 14,
      o3Bid: "3s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 2,
      r1Bid: "1d",
      o2Index: 3,
      o2Bid: "1h",
      r2Index: 10,
      r2Bid: "2nt",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 2,
      r1Bid: "1d",
      o2Index: 3,
      o2Bid: "1h",
      r2Index: 11,
      r2Bid: "3c",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 2,
      r1Bid: "1d",
      o2Index: 3,
      o2Bid: "1h",
      r2Index: 12,
      r2Bid: "3d",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 2,
      r1Bid: "1d",
      o2Index: 3,
      o2Bid: "1h",
      r2Index: 13,
      r2Bid: "3h",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 2,
      r1Bid: "1d",
      o2Index: 3,
      o2Bid: "1h",
      r2Index: 14,
      r2Bid: "3s",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 2,
      r1Bid: "1d",
      o2Index: 3,
      o2Bid: "1h",
      r2Index: 15,
      r2Bid: "3nt",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 2,
      r1Bid: "1d",
      o2Index: 3,
      o2Bid: "1h",
      r2Index: 16,
      r2Bid: "4c",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 21,
      o3Bid: "5c",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 2,
      r1Bid: "1d",
      o2Index: 3,
      o2Bid: "1h",
      r2Index: 17,
      r2Bid: "4d",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 22,
      o3Bid: "5d",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 9,
      r2Bid: "2s",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 10,
      r2Bid: "2nt",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 11,
      r2Bid: "3c",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 12,
      r2Bid: "3d",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 13,
      r2Bid: "3h",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 14,
      r2Bid: "3s",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 15,
      r2Bid: "3nt",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 16,
      r2Bid: "4c",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 17,
      r2Bid: "4d",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 10,
      r2Bid: "2nt",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 11,
      r2Bid: "3c",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 12,
      r2Bid: "3d",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 13,
      r2Bid: "3h",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 14,
      r2Bid: "3s",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 15,
      r2Bid: "3nt",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 16,
      r2Bid: "4c",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 9,
      o2Bid: "2s",
      r2Index: 17,
      r2Bid: "4d",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 7,
      r1Bid: "2d",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 9,
      r2Bid: "2s",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 7,
      r1Bid: "2d",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 10,
      r2Bid: "2nt",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 7,
      r1Bid: "2d",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 11,
      r2Bid: "3c",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 7,
      r1Bid: "2d",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 12,
      r2Bid: "3d",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 7,
      r1Bid: "2d",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 13,
      r2Bid: "3h",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 7,
      r1Bid: "2d",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 14,
      r2Bid: "3s",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 7,
      r1Bid: "2d",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 15,
      r2Bid: "3nt",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 7,
      r1Bid: "2d",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 16,
      r2Bid: "4c",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 21,
      o3Bid: "5c",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 7,
      r1Bid: "2d",
      o2Index: 8,
      o2Bid: "2h",
      r2Index: 17,
      r2Bid: "4d",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 22,
      o3Bid: "5d",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 8,
      r1Bid: "2h",
      o2Index: 13,
      o2Bid: "3h",
      r2Index: 14,
      r2Bid: "3s",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 8,
      r1Bid: "2h",
      o2Index: 13,
      o2Bid: "3h",
      r2Index: 15,
      r2Bid: "3nt",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 8,
      r1Bid: "2h",
      o2Index: 13,
      o2Bid: "3h",
      r2Index: 16,
      r2Bid: "4c",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 8,
      r1Bid: "2h",
      o2Index: 13,
      o2Bid: "3h",
      r2Index: 17,
      r2Bid: "4d",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 9,
      r1Bid: "2s",
      o2Index: 14,
      o2Bid: "3s",
      r2Index: 15,
      r2Bid: "3nt",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 9,
      r1Bid: "2s",
      o2Index: 14,
      o2Bid: "3s",
      r2Index: 16,
      r2Bid: "4c",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 9,
      r1Bid: "2s",
      o2Index: 14,
      o2Bid: "3s",
      r2Index: 17,
      r2Bid: "4d",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 2,
      r1Bid: "1d",
      o2Index: 10,
      o2Bid: "2nt",
      r2Index: 11,
      r2Bid: "3c",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 2,
      r1Bid: "1d",
      o2Index: 10,
      o2Bid: "2nt",
      r2Index: 12,
      r2Bid: "3d",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 2,
      r1Bid: "1d",
      o2Index: 10,
      o2Bid: "2nt",
      r2Index: 13,
      r2Bid: "3h",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 2,
      r1Bid: "1d",
      o2Index: 10,
      o2Bid: "2nt",
      r2Index: 14,
      r2Bid: "3s",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 2,
      r1Bid: "1d",
      o2Index: 10,
      o2Bid: "2nt",
      r2Index: 15,
      r2Bid: "3nt",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 2,
      r1Bid: "1d",
      o2Index: 10,
      o2Bid: "2nt",
      r2Index: 16,
      r2Bid: "4c",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 21,
      o3Bid: "5c",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 2,
      r1Bid: "1d",
      o2Index: 10,
      o2Bid: "2nt",
      r2Index: 17,
      r2Bid: "4d",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 22,
      o3Bid: "5d",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 13,
      o2Bid: "3h",
      r2Index: 14,
      r2Bid: "3s",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 13,
      o2Bid: "3h",
      r2Index: 15,
      r2Bid: "3nt",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 13,
      o2Bid: "3h",
      r2Index: 16,
      r2Bid: "4c",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 3,
      r1Bid: "1h",
      o2Index: 13,
      o2Bid: "3h",
      r2Index: 17,
      r2Bid: "4d",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 14,
      o2Bid: "3s",
      r2Index: 15,
      r2Bid: "3nt",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 14,
      o2Bid: "3s",
      r2Index: 16,
      r2Bid: "4c",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 14,
      o2Bid: "3s",
      r2Index: 17,
      r2Bid: "4d",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 7,
      r1Bid: "2d",
      o2Index: 10,
      o2Bid: "2nt",
      r2Index: 11,
      r2Bid: "3c",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 7,
      r1Bid: "2d",
      o2Index: 10,
      o2Bid: "2nt",
      r2Index: 12,
      r2Bid: "3d",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 7,
      r1Bid: "2d",
      o2Index: 10,
      o2Bid: "2nt",
      r2Index: 13,
      r2Bid: "3h",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 7,
      r1Bid: "2d",
      o2Index: 10,
      o2Bid: "2nt",
      r2Index: 14,
      r2Bid: "3s",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 7,
      r1Bid: "2d",
      o2Index: 10,
      o2Bid: "2nt",
      r2Index: 15,
      r2Bid: "3nt",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 7,
      r1Bid: "2d",
      o2Index: 10,
      o2Bid: "2nt",
      r2Index: 16,
      r2Bid: "4c",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 21,
      o3Bid: "5c",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 7,
      r1Bid: "2d",
      o2Index: 10,
      o2Bid: "2nt",
      r2Index: 17,
      r2Bid: "4d",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o3Index: 22,
      o3Bid: "5d",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 8,
      o2Bid: "2s",
      r2Index: 10,
      r2Bid: "2nt",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 8,
      o2Bid: "2s",
      r2Index: 11,
      r2Bid: "3c",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 8,
      o2Bid: "2s",
      r2Index: 12,
      r2Bid: "3d",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 8,
      o2Bid: "2s",
      r2Index: 13,
      r2Bid: "3h",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 8,
      o2Bid: "2s",
      r2Index: 14,
      r2Bid: "3s",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 8,
      o2Bid: "2s",
      r2Index: 15,
      r2Bid: "3nt",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 8,
      o2Bid: "2s",
      r2Index: 16,
      r2Bid: "4c",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 8,
      o2Bid: "2s",
      r2Index: 17,
      r2Bid: "4d",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 7,
      o2Bid: "2d",
      r2Index: 8,
      r2Bid: "2h",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 7,
      o2Bid: "2d",
      r2Index: 9,
      r2Bid: "2s",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 7,
      o2Bid: "2d",
      r2Index: 10,
      r2Bid: "2nt",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 7,
      o2Bid: "2d",
      r2Index: 11,
      r2Bid: "3c",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 7,
      o2Bid: "2d",
      r2Index: 12,
      r2Bid: "3d",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 7,
      o2Bid: "2d",
      r2Index: 13,
      r2Bid: "3h",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 7,
      o2Bid: "2d",
      r2Index: 14,
      r2Bid: "3s",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 7,
      o2Bid: "2d",
      r2Index: 15,
      r2Bid: "3nt",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 7,
      o2Bid: "2d",
      r2Index: 16,
      r2Bid: "4c",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 21,
      o3Bid: "5c",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 7,
      o2Bid: "2d",
      r2Index: 17,
      r2Bid: "4d",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 22,
      o3Bid: "5d",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 7,
      o2Bid: "2d",
      r2Index: 8,
      r2Bid: "2h",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 7,
      o2Bid: "2d",
      r2Index: 9,
      r2Bid: "2s",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 7,
      o2Bid: "2d",
      r2Index: 10,
      r2Bid: "2nt",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 7,
      o2Bid: "2d",
      r2Index: 11,
      r2Bid: "3c",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 7,
      o2Bid: "2d",
      r2Index: 12,
      r2Bid: "3d",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 15,
      o3Bid: "3nt",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 7,
      o2Bid: "2d",
      r2Index: 13,
      r2Bid: "3h",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 7,
      o2Bid: "2d",
      r2Index: 14,
      r2Bid: "3s",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 7,
      o2Bid: "2d",
      r2Index: 15,
      r2Bid: "3nt",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 7,
      o2Bid: "2d",
      r2Index: 16,
      r2Bid: "4c",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 21,
      o3Bid: "5c",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 6,
      r1Bid: "2c",
      o2Index: 7,
      o2Bid: "2d",
      r2Index: 17,
      r2Bid: "4d",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 22,
      o3Bid: "5d",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 7,
      r1Bid: "2d",
      o2Index: 12,
      o2Bid: "3d",
      r2Index: 13,
      r2Bid: "3h",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 7,
      r1Bid: "2d",
      o2Index: 12,
      o2Bid: "3d",
      r2Index: 14,
      r2Bid: "3s",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 7,
      r1Bid: "2d",
      o2Index: 12,
      o2Bid: "3d",
      r2Index: 15,
      r2Bid: "3nt",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 0,
      o3Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 7,
      r1Bid: "2d",
      o2Index: 12,
      o2Bid: "3d",
      r2Index: 16,
      r2Bid: "4c",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 22,
      o3Bid: "5d",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 7,
      r1Bid: "2d",
      o2Index: 12,
      o2Bid: "3d",
      r2Index: 17,
      r2Bid: "4d",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 22,
      o3Bid: "5d",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 8,
      r1Bid: "2h",
      o2Index: 13,
      o2Bid: "3h",
      r2Index: 14,
      r2Bid: "3s",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 8,
      r1Bid: "2h",
      o2Index: 13,
      o2Bid: "3h",
      r2Index: 15,
      r2Bid: "3nt",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 8,
      r1Bid: "2h",
      o2Index: 13,
      o2Bid: "3h",
      r2Index: 16,
      r2Bid: "4c",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 8,
      r1Bid: "2h",
      o2Index: 13,
      o2Bid: "3h",
      r2Index: 17,
      r2Bid: "4d",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 18,
      o3Bid: "4h",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 9,
      r1Bid: "2s",
      o2Index: 14,
      o2Bid: "3s",
      r2Index: 15,
      r2Bid: "3nt",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 9,
      r1Bid: "2s",
      o2Index: 14,
      o2Bid: "3s",
      r2Index: 16,
      r2Bid: "4c",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 9,
      r1Bid: "2s",
      o2Index: 14,
      o2Bid: "3s",
      r2Index: 17,
      r2Bid: "4d",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 14,
      o2Bid: "3s",
      r2Index: 15,
      r2Bid: "3nt",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 14,
      o2Bid: "3s",
      r2Index: 16,
      r2Bid: "4c",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 19,
      o3Bid: "4s",
    },
    {
      bidder: "o3",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 4,
      r1Bid: "1s",
      o2Index: 14,
      o2Bid: "3s",
      r2Index: 17,
      r2Bid: "4d",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o3Index: 19,
      o3Bid: "4s",
    },
  ];

  var rebidFourCardTwofourCard = fourCard4Card4Card.filter(
    (itemsInArray) =>
      hand.opStrength === itemsInArray.strength &&
      (hand.numS === itemsInArray.minNumS || itemsInArray.minNumS === "") &&
      (hand.numH === itemsInArray.minNumH || itemsInArray.minNumH === "") &&
      (hand.numD === itemsInArray.minNumD || itemsInArray.minNumD === "") &&
      (hand.numC === itemsInArray.minNumC || itemsInArray.minNumC === "") &&
      o1Bid === itemsInArray.o1Bid &&
      r1Bid === itemsInArray.r1Bid &&
      o2Bid === itemsInArray.o2Bid &&
      r2Bid === itemsInArray.r2Bid
  );

  return rebidFourCardTwofourCard;
}
