export default function (hand, o1Bid, r1Bid) {
  var fourCard4Card = [
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 2,
      r1Bid: "1d",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 7,
      o2Bid: "2d",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 3,
      r1Bid: "1h",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 7,
      o2Bid: "2d",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 4,
      r1Bid: "1s",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 7,
      o2Bid: "2d",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 5,
      r1Bid: "1nt",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 0,
      o2Bid: "pass",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 6,
      r1Bid: "2c",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 7,
      o2Bid: "2d",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 7,
      r1Bid: "2d",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 12,
      o2Bid: "3d",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 8,
      r1Bid: "2h",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 12,
      o2Bid: "3d",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 9,
      r1Bid: "2s",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 12,
      o2Bid: "3d",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 10,
      r1Bid: "2nt",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 7,
      o2Bid: "2d",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 3,
      r1Bid: "1h",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 5,
      o2Bid: "1nt",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 4,
      r1Bid: "1s",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 5,
      o2Bid: "1nt",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 5,
      r1Bid: "1nt",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 0,
      o2Bid: "pass",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 6,
      r1Bid: "2c",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 0,
      o2Bid: "pass",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 7,
      r1Bid: "2d",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 12,
      o2Bid: "3d",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 8,
      r1Bid: "2h",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 10,
      o2Bid: "2nt",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 9,
      r1Bid: "2s",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 10,
      o2Bid: "2nt",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 10,
      r1Bid: "2nt",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 11,
      r1Bid: "3c",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: "",
      o2Index: 21,
      o2Bid: "5c",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 12,
      r1Bid: "3d",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: "",
      o2Index: 22,
      o2Bid: "5d",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 2,
      r1Bid: "1d",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 10,
      o2Bid: "2nt",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 3,
      r1Bid: "1h",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 10,
      o2Bid: "2nt",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 4,
      r1Bid: "1s",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 10,
      o2Bid: "2nt",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 5,
      r1Bid: "1nt",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 6,
      r1Bid: "2c",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 10,
      o2Bid: "2nt",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 7,
      r1Bid: "2d",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 8,
      r1Bid: "2h",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 9,
      r1Bid: "2s",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 10,
      r1Bid: "2nt",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 11,
      r1Bid: "3c",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 21,
      o2Bid: "5c",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 12,
      r1Bid: "3d",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 22,
      o2Bid: "5d",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 2,
      r1Bid: "1d",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 2,
      o2Index: 3,
      o2Bid: "1h",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 3,
      r1Bid: "1h",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 6,
      o2Bid: "2c",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 4,
      r1Bid: "1s",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 7,
      o2Bid: "2d",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 5,
      r1Bid: "1nt",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 0,
      o2Bid: "pass",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 6,
      r1Bid: "2c",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 0,
      o2Bid: "pass",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 7,
      r1Bid: "2d",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 12,
      o2Bid: "3d",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 8,
      r1Bid: "2h",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 12,
      o2Bid: "3d",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 9,
      r1Bid: "2s",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 12,
      o2Bid: "3d",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 10,
      r1Bid: "2nt",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 2,
      r1Bid: "1d",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 3,
      o2Bid: "1h",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 2,
      r1Bid: "1d",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 5,
      o2Bid: "1nt",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 3,
      r1Bid: "1h",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 13,
      o2Bid: "3h",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 4,
      r1Bid: "1s",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 5,
      o2Bid: "1nt",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 5,
      r1Bid: "1nt",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 0,
      o2Bid: "pass",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 6,
      r1Bid: "2c",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 0,
      o2Bid: "pass",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 7,
      r1Bid: "2d",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 10,
      o2Bid: "2nt",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 8,
      r1Bid: "2h",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 18,
      o2Bid: "4h",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 9,
      r1Bid: "2s",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 10,
      o2Bid: "2nt",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 10,
      r1Bid: "2nt",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 11,
      r1Bid: "3c",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 21,
      o2Bid: "5c",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 13,
      r1Bid: "3h",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 18,
      o2Bid: "4h",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 2,
      r1Bid: "1d",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 13,
      o2Bid: "3h",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 3,
      r1Bid: "1h",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 18,
      o2Bid: "4h",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 4,
      r1Bid: "1s",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 10,
      o2Bid: "2nt",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 5,
      r1Bid: "1nt",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 6,
      r1Bid: "2c",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 16,
      o2Bid: "4c",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 7,
      r1Bid: "2d",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 8,
      r1Bid: "2h",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 18,
      o2Bid: "4h",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 9,
      r1Bid: "2s",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 10,
      r1Bid: "2nt",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 11,
      r1Bid: "3c",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 21,
      o2Bid: "5c",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 13,
      r1Bid: "3h",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 18,
      o2Bid: "4h",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 2,
      r1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 4,
      o2Bid: "1s",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 3,
      r1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 4,
      o2Bid: "1s",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 4,
      r1Bid: "1s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 9,
      o2Bid: "2s",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 5,
      r1Bid: "1nt",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 0,
      o2Bid: "pass",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 6,
      r1Bid: "2c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 0,
      o2Bid: "pass",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 7,
      r1Bid: "2d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 9,
      o2Bid: "2s",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 8,
      r1Bid: "2h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 9,
      o2Bid: "2s",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 9,
      r1Bid: "2s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 14,
      o2Bid: "3s",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 10,
      r1Bid: "2nt",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 11,
      r1Bid: "3c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 16,
      o2Bid: "4c",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 14,
      r1Bid: "3s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 19,
      o2Bid: "4s",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 2,
      r1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 4,
      o2Bid: "1s",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 3,
      r1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 4,
      o2Bid: "1s",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 4,
      r1Bid: "1s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 14,
      o2Bid: "3s",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 5,
      r1Bid: "1nt",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 0,
      o2Bid: "pass",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 6,
      r1Bid: "2c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 9,
      o2Bid: "2s",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 7,
      r1Bid: "2d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 9,
      o2Bid: "2s",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 8,
      r1Bid: "2h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 9,
      o2Bid: "2s",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 9,
      r1Bid: "2s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 14,
      o2Bid: "3s",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 10,
      r1Bid: "2nt",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 11,
      r1Bid: "3c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 14,
      o2Bid: "3s",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 14,
      r1Bid: "3s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 19,
      o2Bid: "4s",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 2,
      r1Bid: "1d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 9,
      o2Bid: "2s",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 3,
      r1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 9,
      o2Bid: "2s",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 4,
      r1Bid: "1s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 14,
      o2Bid: "3s",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 5,
      r1Bid: "1nt",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 9,
      o2Bid: "2s",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 6,
      r1Bid: "2c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 9,
      o2Bid: "2s",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 7,
      r1Bid: "2d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 9,
      o2Bid: "2s",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 8,
      r1Bid: "2h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 9,
      o2Bid: "2s",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 9,
      r1Bid: "2s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 19,
      o2Bid: "4s",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 10,
      r1Bid: "2nt",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 11,
      r1Bid: "3c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 21,
      o2Bid: "5c",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 14,
      r1Bid: "3s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 4,
      maxNumC: 4,
      weight: 1,
      o2Index: 19,
      o2Bid: "4s",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 8,
      o2Bid: "2h",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 7,
      o2Bid: "2d",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 5,
      r1Bid: "1nt",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 7,
      o2Bid: "2d",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 6,
      r1Bid: "2c",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 8,
      o2Bid: "2h",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 7,
      r1Bid: "2d",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 8,
      o2Bid: "2h",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 8,
      r1Bid: "2h",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 18,
      o2Bid: "4h",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 9,
      r1Bid: "2s",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 13,
      o2Bid: "3h",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 10,
      r1Bid: "2nt",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 12,
      r1Bid: "3d",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 22,
      o2Bid: "5d",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 13,
      r1Bid: "3h",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 18,
      o2Bid: "4h",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 8,
      o2Bid: "2h",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 5,
      o2Bid: "1nt",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 5,
      r1Bid: "1nt",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 0,
      o2Bid: "pass",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 6,
      r1Bid: "2c",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 8,
      o2Bid: "2h",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 7,
      r1Bid: "2d",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 12,
      o2Bid: "3d",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 8,
      r1Bid: "2h",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 18,
      o2Bid: "4h",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 9,
      r1Bid: "2s",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 10,
      o2Bid: "2nt",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 10,
      r1Bid: "2nt",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 12,
      r1Bid: "3d",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 13,
      o2Bid: "3h",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 13,
      r1Bid: "3h",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 13,
      o2Bid: "3h",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 10,
      o2Bid: "2nt",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 5,
      r1Bid: "1nt",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 10,
      o2Bid: "2nt",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 6,
      r1Bid: "2c",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 13,
      o2Bid: "2h",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 7,
      r1Bid: "2d",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 22,
      o2Bid: "5d",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 8,
      r1Bid: "2h",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 18,
      o2Bid: "4h",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 9,
      r1Bid: "2s",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 10,
      r1Bid: "2nt",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 12,
      r1Bid: "3d",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 22,
      o2Bid: "5d",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 13,
      r1Bid: "3h",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 18,
      o2Bid: "4h",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 4,
      o2Bid: "1s",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 9,
      o2Bid: "2s",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 5,
      r1Bid: "1nt",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 0,
      o2Bid: "pass",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 6,
      r1Bid: "2c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 9,
      o2Bid: "2s",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 7,
      r1Bid: "2d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 0,
      o2Bid: "pass",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 8,
      r1Bid: "2h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 9,
      o2Bid: "2s",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 9,
      r1Bid: "2s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 14,
      o2Bid: "3s",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 10,
      r1Bid: "2nt",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 12,
      r1Bid: "3d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 22,
      o2Bid: "5d",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 17,
      r1Bid: "4d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 22,
      o2Bid: "5d",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 14,
      r1Bid: "3s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 19,
      o2Bid: "4s",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 5,
      o2Bid: "1nt",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 9,
      o2Bid: "2s",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 5,
      r1Bid: "1nt",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 0,
      o2Bid: "pass",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 6,
      r1Bid: "2c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 10,
      o2Bid: "2nt",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 7,
      r1Bid: "2d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 9,
      o2Bid: "2s",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 8,
      r1Bid: "2h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 9,
      o2Bid: "2s",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 9,
      r1Bid: "2s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 19,
      o2Bid: "4s",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 10,
      r1Bid: "2nt",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 12,
      r1Bid: "3d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 22,
      o2Bid: "5d",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 14,
      r1Bid: "3s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 19,
      o2Bid: "4s",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 9,
      o2Bid: "2s",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 10,
      o2Bid: "2nt",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 5,
      r1Bid: "1nt",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 10,
      o2Bid: "2nt",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 6,
      r1Bid: "2c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 9,
      o2Bid: "2s",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 7,
      r1Bid: "2d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 9,
      o2Bid: "2s",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 8,
      r1Bid: "2h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 9,
      o2Bid: "2s",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 9,
      r1Bid: "2s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 19,
      o2Bid: "4s",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 10,
      r1Bid: "2nt",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 12,
      r1Bid: "3d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 22,
      o2Bid: "5d",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 14,
      r1Bid: "3s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: "",
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 19,
      o2Bid: "4s",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 4,
      r1Bid: "1s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 9,
      o2Bid: "2s",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 5,
      r1Bid: "1nt",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 0,
      o2Bid: "pass",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 6,
      r1Bid: "2c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 9,
      o2Bid: "2s",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 7,
      r1Bid: "2d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 9,
      o2Bid: "2s",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 8,
      r1Bid: "2h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 8,
      o2Bid: "3h",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 9,
      r1Bid: "2s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 14,
      o2Bid: "3s",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 10,
      r1Bid: "2nt",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 12,
      r1Bid: "3h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 18,
      o2Bid: "4h",
    },
    {
      bidder: "o2",
      minTP: 12,
      maxTP: 14,
      strength: "min",
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 14,
      r1Bid: "3s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 19,
      o2Bid: "4s",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 4,
      r1Bid: "1s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 14,
      o2Bid: "3s",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 5,
      r1Bid: "1nt",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 0,
      o2Bid: "pass",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 6,
      r1Bid: "2c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 10,
      o2Bid: "2nt",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 7,
      r1Bid: "2d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 10,
      o2Bid: "2nt",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 8,
      r1Bid: "2h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 13,
      o2Bid: "3h",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 9,
      r1Bid: "2s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 19,
      o2Bid: "4s",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 10,
      r1Bid: "2nt",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 12,
      r1Bid: "3h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 18,
      o2Bid: "4h",
    },
    {
      bidder: "o2",
      minTP: 15,
      maxTP: 16,
      strength: "med",
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 14,
      r1Bid: "3s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 19,
      o2Bid: "4s",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 4,
      r1Bid: "1s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 14,
      o2Bid: "3s",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 5,
      r1Bid: "1nt",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 10,
      o2Bid: "2nt",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 6,
      r1Bid: "2c",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 9,
      o2Bid: "2s",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 7,
      r1Bid: "2d",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 9,
      o2Bid: "2s",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 8,
      r1Bid: "2h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 18,
      o2Bid: "4h",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 9,
      r1Bid: "2s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 19,
      o2Bid: "4s",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 10,
      r1Bid: "2nt",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 12,
      r1Bid: "3h",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 18,
      o2Bid: "4h",
    },
    {
      bidder: "o2",
      minTP: 17,
      maxTP: 19,
      strength: "max",
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 14,
      r1Bid: "3s",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 4,
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      weight: 1,
      o2Index: 19,
      o2Bid: "4s",
    },
  ];

  // remember to update variable names in the array

  var rebidFourCard4Card = fourCard4Card.filter(
    (itemsInArray) =>
      hand.opStrength === itemsInArray.strength &&
      (hand.numS >= itemsInArray.minNumS || itemsInArray.minNumS === "") &&
      (hand.numS <= itemsInArray.maxNumS || itemsInArray.maxNumS === "") &&
      (hand.numH >= itemsInArray.minNumH || itemsInArray.minNumH === "") &&
      (hand.numH <= itemsInArray.maxNumH || itemsInArray.maxNumH === "") &&
      (hand.numD >= itemsInArray.minNumD || itemsInArray.minNumD === "") &&
      (hand.numD <= itemsInArray.maxNumD || itemsInArray.maxNumD === "") &&
      (hand.numC >= itemsInArray.minNumC || itemsInArray.minNumC === "") &&
      (hand.numC <= itemsInArray.maxNumC || itemsInArray.maxNumC === "") &&
      o1Bid === itemsInArray.o1Bid &&
      r1Bid === itemsInArray.r1Bid
  );

  return rebidFourCard4Card;
}
