export default function (hand, o1Bid, oc1Bid, r1Bid) {
  var threeFourCardSuits = [
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o2Index: 8,
      o2Bid: "2h",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o2Index: 6,
      o2Bid: "2c",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 5,
      r1Bid: "1nt",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o2Index: 6,
      o2Bid: "2c",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 6,
      r1Bid: "2c",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o2Index: 11,
      o2Bid: "3c",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 7,
      r1Bid: "2d",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o2Index: 12,
      o2Bid: "3d",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 8,
      r1Bid: "2h",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o2Index: 13,
      o2Bid: "3h",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 9,
      r1Bid: "2s",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o2Index: 11,
      o2Bid: "3c",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 10,
      r1Bid: "2nt",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 15,
      r1Bid: "3nt",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o2Index: 0,
      o2Bid: "pass",
    },
    {
      bidder: "o3",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 16,
      r1Bid: "4c",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o2Index: 21,
      o2Bid: "5c",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 17,
      r1Bid: "4d",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o2Index: 22,
      o2Bid: "5d",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 18,
      r1Bid: "4h",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o2Index: 0,
      o2Bid: "pass",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o2Index: 8,
      o2Bid: "2h",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o2Index: 6,
      o2Bid: "2c",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 5,
      r1Bid: "1nt",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o2Index: 0,
      o2Bid: "pass",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 6,
      r1Bid: "2c",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o2Index: 11,
      o2Bid: "3c",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 7,
      r1Bid: "2d",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o2Index: 12,
      o2Bid: "3d",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 8,
      r1Bid: "2h",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o2Index: 13,
      o2Bid: "3h",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 9,
      r1Bid: "2s",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o2Index: 10,
      o2Bid: "2nt",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 10,
      r1Bid: "2nt",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 15,
      r1Bid: "3nt",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o2Index: 0,
      o2Bid: "pass",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 16,
      r1Bid: "4c",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o2Index: 21,
      o2Bid: "5c",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 17,
      r1Bid: "4d",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o2Index: 22,
      o2Bid: "5d",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 18,
      r1Bid: "4h",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o2Index: 0,
      o2Bid: "pass",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o2Index: 18,
      o2Bid: "3h",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o2Index: 10,
      o2Bid: "2nt",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 5,
      r1Bid: "1nt",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 6,
      r1Bid: "2c",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o2Index: 16,
      o2Bid: "4c",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 7,
      r1Bid: "2d",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o2Index: 17,
      o2Bid: "4d",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 8,
      r1Bid: "2h",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o2Index: 18,
      o2Bid: "4h",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 9,
      r1Bid: "2s",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 10,
      r1Bid: "2nt",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 15,
      r1Bid: "3nt",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o2Index: 30,
      o2Bid: "6nt",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 16,
      r1Bid: "4c",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o2Index: 26,
      o2Bid: "6c",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 17,
      r1Bid: "4d",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o2Index: 27,
      o2Bid: "6d",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 18,
      r1Bid: "4h",
      numS: 1,
      numH: 4,
      numD: 4,
      numC: 4,
      o2Index: 28,
      o2Bid: "6h",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o2Index: 4,
      o2Bid: "1s",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o2Index: 9,
      o2Bid: "2s",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 5,
      r1Bid: "1nt",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o2Index: 6,
      o2Bid: "2c",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 6,
      r1Bid: "2c",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o2Index: 11,
      o2Bid: "3c",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 7,
      r1Bid: "2d",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o2Index: 12,
      o2Bid: "3d",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 8,
      r1Bid: "2h",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o2Index: 9,
      o2Bid: "2s",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 9,
      r1Bid: "2s",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o2Index: 11,
      o2Bid: "3c",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 10,
      r1Bid: "2nt",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 15,
      r1Bid: "3nt",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o2Index: 0,
      o2Bid: "pass",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 16,
      r1Bid: "4c",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o2Index: 21,
      o2Bid: "5c",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 17,
      r1Bid: "4d",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o2Index: 22,
      o2Bid: "5d",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 18,
      r1Bid: "3s",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o2Index: 19,
      o2Bid: "4s",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o2Index: 4,
      o2Bid: "1s",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o2Index: 9,
      o2Bid: "2s",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 5,
      r1Bid: "1nt",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o2Index: 0,
      o2Bid: "pass",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 6,
      r1Bid: "2c",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o2Index: 11,
      o2Bid: "3c",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 7,
      r1Bid: "2d",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o2Index: 12,
      o2Bid: "3d",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 8,
      r1Bid: "2h",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o2Index: 9,
      o2Bid: "2s",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 9,
      r1Bid: "2s",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o2Index: 11,
      o2Bid: "3c",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 10,
      r1Bid: "2nt",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 15,
      r1Bid: "3nt",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o2Index: 0,
      o2Bid: "pass",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 16,
      r1Bid: "4c",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o2Index: 21,
      o2Bid: "5c",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 17,
      r1Bid: "4d",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o2Index: 22,
      o2Bid: "5d",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 18,
      r1Bid: "4h",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o2Index: 19,
      o2Bid: "4s",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 3,
      r1Bid: "1h",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o2Index: 4,
      o2Bid: "1s",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 4,
      r1Bid: "1s",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o2Index: 9,
      o2Bid: "2s",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 5,
      r1Bid: "1nt",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o2Index: 6,
      o2Bid: "2c",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 6,
      r1Bid: "2c",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o2Index: 11,
      o2Bid: "3c",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 7,
      r1Bid: "2d",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o2Index: 12,
      o2Bid: "3d",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 8,
      r1Bid: "2h",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o2Index: 9,
      o2Bid: "2s",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 9,
      r1Bid: "2s",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o2Index: 11,
      o2Bid: "3c",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 10,
      r1Bid: "2nt",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 15,
      r1Bid: "3nt",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o2Index: 0,
      o2Bid: "pass",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 16,
      r1Bid: "4c",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o2Index: 21,
      o2Bid: "5c",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 17,
      r1Bid: "4d",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o2Index: 22,
      o2Bid: "5d",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 2,
      o1Bid: "1d",
      r1Index: 18,
      r1Bid: "4h",
      numS: 4,
      numH: 1,
      numD: 4,
      numC: 4,
      o2Index: 19,
      o2Bid: "4s",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 2,
      r1Bid: "1d",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 3,
      o2Bid: "1h",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 3,
      r1Bid: "1h",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 8,
      o2Bid: "2h",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 4,
      r1Bid: "1s",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 9,
      o2Bid: "2s",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 5,
      r1Bid: "1nt",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 0,
      o2Bid: "pass",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 6,
      r1Bid: "2c",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 11,
      o2Bid: "3c",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 7,
      r1Bid: "2d",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 8,
      o2Bid: "2h",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 8,
      r1Bid: "2h",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 13,
      o2Bid: "3h",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 9,
      r1Bid: "2s",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 14,
      o2Bid: "3s",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 10,
      r1Bid: "2nt",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 15,
      r1Bid: "3nt",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 0,
      o2Bid: "pass",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 16,
      r1Bid: "4c",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 21,
      o2Bid: "5c",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 17,
      r1Bid: "4d",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 22,
      o2Bid: "5d",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 13,
      r1Bid: "3h",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 18,
      o2Bid: "4h",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 2,
      r1Bid: "1d",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 3,
      o2Bid: "1h",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 3,
      r1Bid: "1h",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 8,
      o2Bid: "2h",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 4,
      r1Bid: "1s",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 9,
      o2Bid: "2s",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 5,
      r1Bid: "1nt",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 0,
      o2Bid: "pass",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 6,
      r1Bid: "2c",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 11,
      o2Bid: "3c",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 7,
      r1Bid: "2d",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 8,
      o2Bid: "2h",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 8,
      r1Bid: "2h",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 13,
      o2Bid: "3h",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 9,
      r1Bid: "2s",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 14,
      o2Bid: "3s",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 10,
      r1Bid: "2nt",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 15,
      r1Bid: "3nt",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 0,
      o2Bid: "pass",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 16,
      r1Bid: "4c",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 21,
      o2Bid: "5c",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 17,
      r1Bid: "4d",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 22,
      o2Bid: "5d",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 13,
      r1Bid: "3h",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 18,
      o2Bid: "4h",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 2,
      r1Bid: "1d",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 10,
      o2Bid: "2nt",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 3,
      r1Bid: "1h",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 13,
      o2Bid: "3h",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 4,
      r1Bid: "1s",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 14,
      o2Bid: "3s",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 5,
      r1Bid: "1nt",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 6,
      r1Bid: "2c",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 21,
      o2Bid: "5c",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 7,
      r1Bid: "2d",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 10,
      o2Bid: "2nt",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 8,
      r1Bid: "2h",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 18,
      o2Bid: "4h",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 9,
      r1Bid: "2s",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 19,
      o2Bid: "4s",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 10,
      r1Bid: "2nt",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 15,
      r1Bid: "3nt",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 0,
      o2Bid: "pass",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 16,
      r1Bid: "4c",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 21,
      o2Bid: "5c",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 17,
      r1Bid: "4d",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 22,
      o2Bid: "5d",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 1,
      o1Bid: "1c",
      r1Index: 13,
      r1Bid: "3h",
      numS: 4,
      numH: 4,
      numD: 1,
      numC: 4,
      o2Index: 18,
      o2Bid: "4h",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 4,
      r1Bid: "1s",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o2Index: 8,
      o2Bid: "2h",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 5,
      r1Bid: "1nt",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o2Index: 0,
      o2Bid: "pass",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 6,
      r1Bid: "2c",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o2Index: 7,
      o2Bid: "2d",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 7,
      r1Bid: "2d",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o2Index: 12,
      o2Bid: "3d",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 8,
      r1Bid: "2h",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o2Index: 13,
      o2Bid: "3h",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 9,
      r1Bid: "2s",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o2Index: 14,
      o2Bid: "3s",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 10,
      r1Bid: "2nt",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o2Index: 0,
      o2Bid: "pass",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 15,
      r1Bid: "3nt",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o2Index: 0,
      o2Bid: "pass",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 16,
      r1Bid: "4c",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o2Index: 21,
      o2Bid: "5c",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 17,
      r1Bid: "4d",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o2Index: 22,
      o2Bid: "5d",
    },
    {
      bidder: "o2",
      strength: "min",
      minTP: 12,
      maxTP: 14,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 13,
      r1Bid: "3h",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o2Index: 18,
      o2Bid: "4h",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 4,
      r1Bid: "1s",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o2Index: 8,
      o2Bid: "2s",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 5,
      r1Bid: "1nt",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o2Index: 0,
      o2Bid: "pass",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 6,
      r1Bid: "2c",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o2Index: 7,
      o2Bid: "2d",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 7,
      r1Bid: "2d",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o2Index: 12,
      o2Bid: "3d",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 8,
      r1Bid: "2h",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o2Index: 13,
      o2Bid: "3h",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 9,
      r1Bid: "2s",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o2Index: 14,
      o2Bid: "3s",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 10,
      r1Bid: "2nt",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 15,
      r1Bid: "3nt",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o2Index: 0,
      o2Bid: "pass",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 16,
      r1Bid: "3s",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o2Index: 19,
      o2Bid: "4s",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 17,
      r1Bid: "4d",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o2Index: 22,
      o2Bid: "5d",
    },
    {
      bidder: "o2",
      strength: "med",
      minTP: 15,
      maxTP: 16,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 18,
      r1Bid: "4h",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o2Index: 18,
      o2Bid: "4h",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 4,
      r1Bid: "1s",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o2Index: 14,
      o2Bid: "3s",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 5,
      r1Bid: "1nt",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 6,
      r1Bid: "2c",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 7,
      r1Bid: "2d",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 8,
      r1Bid: "2h",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o2Index: 18,
      o2Bid: "4h",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 9,
      r1Bid: "2s",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o2Index: 19,
      o2Bid: "4s",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 10,
      r1Bid: "2nt",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o2Index: 15,
      o2Bid: "3nt",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 15,
      r1Bid: "3nt",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o2Index: 0,
      o2Bid: "pass",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 16,
      r1Bid: "4s",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o2Index: 29,
      o2Bid: "6s",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 17,
      r1Bid: "4d",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o2Index: 27,
      o2Bid: "6d",
    },
    {
      bidder: "o2",
      strength: "max",
      minTP: 17,
      maxTP: 19,
      o1Index: 3,
      o1Bid: "1h",
      r1Index: 18,
      r1Bid: "4h",
      numS: 4,
      numH: 4,
      numD: 4,
      numC: 1,
      o2Index: 28,
      o2Bid: "6h",
    },
  ];

  var rebidThreeFourCardSuits = threeFourCardSuits.filter(
    (itemsInArray) =>
      hand.opStrength === itemsInArray.strength &&
      (hand.numS === itemsInArray.numS || itemsInArray.numS === "") &&
      (hand.numH === itemsInArray.numH || itemsInArray.numH === "") &&
      (hand.numD === itemsInArray.numD || itemsInArray.numD === "") &&
      (hand.numC === itemsInArray.numC || itemsInArray.numC === "") &&
      o1Bid === itemsInArray.o1Bid &&
      r1Bid === itemsInArray.r1Bid
  );

  return rebidThreeFourCardSuits;
}
