var fiveCardFourCardFourCard = [
  {
    bidder: "o1",
    weight: 1,
    minTP: 13,
    maxTP: 15,
    strength: "min",
    numS: 5,
    numH: 4,
    numD: 4,
    numC: "",
    o1Index: 4,
    o1Bid: "1s",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 16,
    maxTP: 17,
    strength: "med",
    numS: 5,
    numH: 4,
    numD: 4,
    numC: "",
    o1Index: 4,
    o1Bid: "1s",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 18,
    maxTP: 19,
    strength: "max",
    numS: 5,
    numH: 4,
    numD: 4,
    numC: "",
    o1Index: 4,
    o1Bid: "1s",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 13,
    maxTP: 15,
    strength: "min",
    numS: 5,
    numH: 4,
    numD: "",
    numC: 4,
    o1Index: 4,
    o1Bid: "1s",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 16,
    maxTP: 17,
    strength: "med",
    numS: 5,
    numH: 4,
    numD: "",
    numC: 4,
    o1Index: 4,
    o1Bid: "1s",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 18,
    maxTP: 19,
    strength: "max",
    numS: 5,
    numH: 4,
    numD: "",
    numC: 4,
    o1Index: 4,
    o1Bid: "1s",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 13,
    maxTP: 15,
    strength: "min",
    numS: 5,
    numH: "",
    numD: 4,
    numC: 4,
    o1Index: 4,
    o1Bid: "1s",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 16,
    maxTP: 17,
    strength: "med",
    numS: 5,
    numH: "",
    numD: 4,
    numC: 4,
    o1Index: 4,
    o1Bid: "1s",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 18,
    maxTP: 19,
    strength: "max",
    numS: 5,
    numH: "",
    numD: 4,
    numC: 4,
    o1Index: 4,
    o1Bid: "1s",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 13,
    maxTP: 15,
    strength: "min",
    numS: 4,
    numH: 5,
    numD: 4,
    numC: "",
    o1Index: 3,
    o1Bid: "1h",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 16,
    maxTP: 17,
    strength: "med",
    numS: 4,
    numH: 5,
    numD: 4,
    numC: "",
    o1Index: 3,
    o1Bid: "1h",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 18,
    maxTP: 19,
    strength: "max",
    numS: 4,
    numH: 5,
    numD: 4,
    numC: "",
    o1Index: 3,
    o1Bid: "1h",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 13,
    maxTP: 15,
    strength: "min",
    numS: 4,
    numH: 5,
    numD: "",
    numC: 4,
    o1Index: 3,
    o1Bid: "1h",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 16,
    maxTP: 17,
    strength: "med",
    numS: 4,
    numH: 5,
    numD: "",
    numC: 4,
    o1Index: 3,
    o1Bid: "1h",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 18,
    maxTP: 19,
    strength: "max",
    numS: 4,
    numH: 5,
    numD: "",
    numC: 4,
    o1Index: 3,
    o1Bid: "1h",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 13,
    maxTP: 15,
    strength: "min",
    numS: "",
    numH: 5,
    numD: 4,
    numC: 4,
    o1Index: 3,
    o1Bid: "1h",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 16,
    maxTP: 17,
    strength: "med",
    numS: "",
    numH: 5,
    numD: 4,
    numC: 4,
    o1Index: 3,
    o1Bid: "1h",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 18,
    maxTP: 19,
    strength: "max",
    numS: "",
    numH: 5,
    numD: 4,
    numC: 4,
    o1Index: 3,
    o1Bid: "1h",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 13,
    maxTP: 15,
    strength: "min",
    numS: 4,
    numH: 4,
    numD: 5,
    numC: "",
    o1Index: 2,
    o1Bid: "1d",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 16,
    maxTP: 17,
    strength: "med",
    numS: 4,
    numH: 4,
    numD: 5,
    numC: "",
    o1Index: 2,
    o1Bid: "1d",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 18,
    maxTP: 19,
    strength: "max",
    numS: 4,
    numH: 4,
    numD: 5,
    numC: "",
    o1Index: 2,
    o1Bid: "1d",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 13,
    maxTP: 15,
    strength: "min",
    numS: 4,
    numH: "",
    numD: 5,
    numC: 4,
    o1Index: 2,
    o1Bid: "1d",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 16,
    maxTP: 17,
    strength: "med",
    numS: 4,
    numH: "",
    numD: 5,
    numC: 4,
    o1Index: 2,
    o1Bid: "1d",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 18,
    maxTP: 19,
    strength: "max",
    numS: 4,
    numH: "",
    numD: 5,
    numC: 4,
    o1Index: 2,
    o1Bid: "1d",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 13,
    maxTP: 15,
    strength: "min",
    numS: "",
    numH: 4,
    numD: 5,
    numC: 4,
    o1Index: 2,
    o1Bid: "1d",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 16,
    maxTP: 17,
    strength: "med",
    numS: "",
    numH: 4,
    numD: 5,
    numC: 4,
    o1Index: 2,
    o1Bid: "1d",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 18,
    maxTP: 19,
    strength: "max",
    numS: "",
    numH: 4,
    numD: 5,
    numC: 4,
    o1Index: 2,
    o1Bid: "1d",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 13,
    maxTP: 15,
    strength: "min",
    numS: "",
    numH: 4,
    numD: 4,
    numC: 5,
    o1Index: 1,
    o1Bid: "1c",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 16,
    maxTP: 17,
    strength: "med",
    numS: "",
    numH: 4,
    numD: 4,
    numC: 5,
    o1Index: 1,
    o1Bid: "1c",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 18,
    maxTP: 19,
    strength: "max",
    numS: "",
    numH: 4,
    numD: 4,
    numC: 5,
    o1Index: 1,
    o1Bid: "1c",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 13,
    maxTP: 15,
    strength: "min",
    numS: 4,
    numH: 4,
    numD: "",
    numC: 5,
    o1Index: 1,
    o1Bid: "1c",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 16,
    maxTP: 17,
    strength: "med",
    numS: 4,
    numH: 4,
    numD: "",
    numC: 5,
    o1Index: 1,
    o1Bid: "1c",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 18,
    maxTP: 19,
    strength: "max",
    numS: 4,
    numH: 4,
    numD: "",
    numC: 5,
    o1Index: 1,
    o1Bid: "1c",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 13,
    maxTP: 15,
    strength: "min",
    numS: 4,
    numH: "",
    numD: 4,
    numC: 5,
    o1Index: 1,
    o1Bid: "1c",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 16,
    maxTP: 17,
    strength: "med",
    numS: 4,
    numH: "",
    numD: 4,
    numC: 5,
    o1Index: 1,
    o1Bid: "1c",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 18,
    maxTP: 19,
    strength: "max",
    numS: 4,
    numH: "",
    numD: 4,
    numC: 5,
    o1Index: 1,
    o1Bid: "1c",
  },
];

var rebidFiveCardFourCardFourCard = fiveCardFourCardFourCard.filter(
  (itemsInArray) =>
    hand.strength === itemsInArray.strength &&
    (hand.numS === itemsInArray.numS || itemsInArray.numS === "") &&
    (hand.numH === itemsInArray.numH || itemsInArray.numH === "") &&
    (hand.numD === itemsInArray.numD || itemsInArray.numD === "") &&
    (hand.numC === itemsInArray.numC || itemsInArray.numC === "")
);
