var fourCardFourCardFourCard = [
  {
    bidder: "o1",
    minTP: 13,
    maxTP: 15,
    weight: 1,
    strength: "min",
    numS: 4,
    numH: 4,
    numD: 1,
    numC: 4,
    o1Index: 1,
    o1bid: "1c",
  },
  {
    bidder: "o1",
    minTP: 16,
    maxTP: 17,
    weight: 1,
    strength: "med",
    numS: 4,
    numH: 4,
    numD: 1,
    numC: 4,
    o1Index: 1,
    o1bid: "1c",
  },
  {
    bidder: "o1",
    minTP: 18,
    maxTP: 19,
    weight: 1,
    strength: "max",
    numS: 4,
    numH: 4,
    numD: 1,
    numC: 4,
    o1Index: 1,
    o1bid: "1c",
  },
  {
    bidder: "o1",
    minTP: 13,
    maxTP: 15,
    weight: 1,
    strength: "min",
    numS: 1,
    numH: 4,
    numD: 4,
    numC: 4,
    o1Index: 1,
    o1bid: "1c",
  },
  {
    bidder: "o1",
    minTP: 16,
    maxTP: 17,
    weight: 1,
    strength: "med",
    numS: 1,
    numH: 4,
    numD: 4,
    numC: 4,
    o1Index: 1,
    o1bid: "1c",
  },
  {
    bidder: "o1",
    minTP: 18,
    maxTP: 19,
    weight: 1,
    strength: "max",
    numS: 1,
    numH: 4,
    numD: 4,
    numC: 4,
    o1Index: 1,
    o1bid: "1c",
  },
  {
    bidder: "o1",
    minTP: 13,
    maxTP: 15,
    weight: 1,
    strength: "min",
    numS: 4,
    numH: 1,
    numD: 4,
    numC: 4,
    o1Index: 2,
    o1bid: "1d",
  },
  {
    bidder: "o1",
    minTP: 16,
    maxTP: 17,
    weight: 1,
    strength: "med",
    numS: 4,
    numH: 1,
    numD: 4,
    numC: 4,
    o1Index: 2,
    o1bid: "1d",
  },
  {
    bidder: "o1",
    minTP: 18,
    maxTP: 19,
    weight: 1,
    strength: "max",
    numS: 4,
    numH: 1,
    numD: 4,
    numC: 4,
    o1Index: 2,
    o1bid: "1d",
  },
  {
    bidder: "o1",
    minTP: 13,
    maxTP: 15,
    weight: 1,
    strength: "min",
    numS: 4,
    numH: 4,
    numD: 4,
    numC: 1,
    o1Index: 3,
    o1bid: "1d",
  },
  {
    bidder: "o1",
    minTP: 16,
    maxTP: 17,
    weight: 1,
    strength: "med",
    numS: 4,
    numH: 4,
    numD: 4,
    numC: 1,
    o1Index: 3,
    o1bid: "1d",
  },
  {
    bidder: "o1",
    minTP: 18,
    maxTP: 19,
    weight: 1,
    strength: "max",
    numS: 4,
    numH: 4,
    numD: 4,
    numC: 1,
    o1Index: 3,
    o1bid: "1d",
  },
];

var rebidFourCardFourCardFourCard = fourCardFourCardFourCard.filter(
  (itemsInArray) =>
    hand.strength === itemsInArray.strength &&
    (hand.numS >= itemsInArray.numS || itemsInArray.numS === "") &&
    (hand.numS <= itemsInArray.numS || itemsInArray.numS === "") &&
    (hand.numH >= itemsInArray.numH || itemsInArray.numH === "") &&
    (hand.numH <= itemsInArray.numH || itemsInArray.numH === "") &&
    (hand.numD >= itemsInArray.numD || itemsInArray.numD === "") &&
    (hand.numD <= itemsInArray.numD || itemsInArray.numD === "") &&
    (hand.numC >= itemsInArray.numC || itemsInArray.numC === "") &&
    (hand.numC <= itemsInArray.numC || itemsInArray.numC === "")
);
