var oneLongSuit = [
  {
    bidder: "o1",
    minTP: 12,
    maxTP: 14,
    strength: "min",
    minNumS: "",
    maxNumS: 3,
    minNumH: "",
    maxNumH: 3,
    minNumD: "",
    maxNumD: 3,
    minNumC: 5,
    maxNumC: "",
    o1Index: 1,
    o1Bid: "1c",
  },
  {
    bidder: "o1",
    minTP: 15,
    maxTP: 16,
    strength: "med",
    minNumS: "",
    maxNumS: 3,
    minNumH: "",
    maxNumH: 3,
    minNumD: "",
    maxNumD: 3,
    minNumC: 5,
    maxNumC: "",
    o1Index: 1,
    o1Bid: "1c",
  },
  {
    bidder: "o1",
    minTP: 17,
    maxTP: 19,
    strength: "max",
    minNumS: "",
    maxNumS: 3,
    minNumH: "",
    maxNumH: 3,
    minNumD: "",
    maxNumD: 3,
    minNumC: 5,
    maxNumC: "",
    o1Index: 1,
    o1Bid: "1c",
  },
  {
    bidder: "o1",
    minTP: 12,
    maxTP: 14,
    strength: "min",
    minNumS: "",
    maxNumS: 3,
    minNumH: "",
    maxNumH: 3,
    minNumD: 5,
    maxNumD: "",
    minNumC: "",
    maxNumC: 3,
    o1Index: 2,
    o1Bid: "1d",
  },
  {
    bidder: "o1",
    minTP: 15,
    maxTP: 16,
    strength: "med",
    minNumS: "",
    maxNumS: 3,
    minNumH: "",
    maxNumH: 3,
    minNumD: 5,
    maxNumD: "",
    minNumC: "",
    maxNumC: 3,
    o1Index: 2,
    o1Bid: "1d",
  },
  {
    bidder: "o1",
    minTP: 17,
    maxTP: 19,
    strength: "max",
    minNumS: "",
    maxNumS: 3,
    minNumH: "",
    maxNumH: 3,
    minNumD: 5,
    maxNumD: "",
    minNumC: "",
    maxNumC: 3,
    o1Index: 2,
    o1Bid: "1d",
  },
  {
    bidder: "o1",
    minTP: 12,
    maxTP: 14,
    strength: "min",
    minNumS: "",
    maxNumS: 3,
    minNumH: 5,
    maxNumH: "",
    minNumD: "",
    maxNumD: 3,
    minNumC: "",
    maxNumC: 3,
    o1Index: 3,
    o1Bid: "1h",
  },
  {
    bidder: "o1",
    minTP: 15,
    maxTP: 16,
    strength: "med",
    minNumS: "",
    maxNumS: 3,
    minNumH: 5,
    maxNumH: "",
    minNumD: "",
    maxNumD: 3,
    minNumC: "",
    maxNumC: 3,
    o1Index: 3,
    o1Bid: "1h",
  },
  {
    bidder: "o1",
    minTP: 17,
    maxTP: 19,
    strength: "max",
    minNumS: "",
    maxNumS: 3,
    minNumH: 5,
    maxNumH: "",
    minNumD: "",
    maxNumD: 3,
    minNumC: "",
    maxNumC: 3,
    o1Index: 3,
    o1Bid: "1h",
  },
  {
    bidder: "o1",
    minTP: 12,
    maxTP: 14,
    strength: "min",
    minNumS: 5,
    maxNumS: "",
    minNumH: "",
    maxNumH: 3,
    minNumD: "",
    maxNumD: 3,
    minNumC: "",
    maxNumC: 3,
    o1Index: 4,
    o1Bid: "1s",
  },
  {
    bidder: "o1",
    minTP: 15,
    maxTP: 16,
    strength: "med",
    minNumS: 5,
    maxNumS: "",
    minNumH: "",
    maxNumH: 3,
    minNumD: "",
    maxNumD: 3,
    minNumC: "",
    maxNumC: 3,
    o1Index: 4,
    o1Bid: "1s",
  },
  {
    bidder: "o1",
    minTP: 17,
    maxTP: 19,
    strength: "max",
    minNumS: 5,
    maxNumS: "",
    minNumH: "",
    maxNumH: 3,
    minNumD: "",
    maxNumD: 3,
    minNumC: "",
    maxNumC: 3,
    o1Index: 4,
    o1Bid: "1s",
  },
];

var rebidOneLongSuit = oneLongSuit.filter(
  (itemsInArray) =>
    hand.strength === itemsInArray.strength &&
    (hand.numS >= itemsInArray.numS || itemsInArray.numS === "") &&
    (hand.numS <= itemsInArray.numS || itemsInArray.numS === "") &&
    (hand.numH >= itemsInArray.numH || itemsInArray.numH === "") &&
    (hand.numH <= itemsInArray.numH || itemsInArray.numH === "") &&
    (hand.numD >= itemsInArray.numD || itemsInArray.numD === "") &&
    (hand.numD <= itemsInArray.numD || itemsInArray.numD === "") &&
    (hand.numC >= itemsInArray.numC || itemsInArray.numC === "") &&
    (hand.numC <= itemsInArray.numC || itemsInArray.numC === "")
);
