var sixCardFourCard = [
  {
    bidder: "o1",
    weight: 1,
    minTP: 13,
    maxTP: 15,
    strength: "min",
    minNumS: "",
    maxNumS: 3,
    minNumH: "",
    maxNumH: 3,
    minNumD: 4,
    maxNumD: 4,
    minNumC: 6,
    maxNumC: 6,
    sLong: "c",
    o1bIndex: 1,
    o1Bid: "1c",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 16,
    maxTP: 17,
    strength: "med",
    minNumS: "",
    maxNumS: 3,
    minNumH: "",
    maxNumH: 3,
    minNumD: 4,
    maxNumD: 4,
    minNumC: 6,
    maxNumC: 6,
    sLong: "c",
    o1bIndex: 1,
    o1Bid: "1c",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 18,
    maxTP: 19,
    strength: "max",
    minNumS: "",
    maxNumS: 3,
    minNumH: "",
    maxNumH: 3,
    minNumD: 4,
    maxNumD: 4,
    minNumC: 6,
    maxNumC: 6,
    sLong: "c",
    o1bIndex: 1,
    o1Bid: "1c",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 13,
    maxTP: 15,
    strength: "min",
    minNumS: "",
    maxNumS: 3,
    minNumH: 4,
    maxNumH: 4,
    minNumD: "",
    maxNumD: 3,
    minNumC: 6,
    maxNumC: 6,
    sLong: "c",
    o1bIndex: 1,
    o1Bid: "1c",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 16,
    maxTP: 17,
    strength: "med",
    minNumS: "",
    maxNumS: 3,
    minNumH: 4,
    maxNumH: 4,
    minNumD: "",
    maxNumD: 3,
    minNumC: 6,
    maxNumC: 6,
    sLong: "c",
    o1bIndex: 1,
    o1Bid: "1c",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 18,
    maxTP: 19,
    strength: "max",
    minNumS: "",
    maxNumS: 3,
    minNumH: 4,
    maxNumH: 4,
    minNumD: "",
    maxNumD: 3,
    minNumC: 6,
    maxNumC: 6,
    sLong: "c",
    o1bIndex: 1,
    o1Bid: "1c",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 13,
    maxTP: 15,
    strength: "min",
    minNumS: 4,
    maxNumS: 4,
    minNumH: "",
    maxNumH: 3,
    minNumD: "",
    maxNumD: 3,
    minNumC: 6,
    maxNumC: 6,
    sLong: "c",
    o1bIndex: 1,
    o1Bid: "1c",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 16,
    maxTP: 17,
    strength: "med",
    minNumS: 4,
    maxNumS: 4,
    minNumH: "",
    maxNumH: 3,
    minNumD: "",
    maxNumD: 3,
    minNumC: 6,
    maxNumC: 6,
    sLong: "c",
    o1bIndex: 1,
    o1Bid: "1c",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 18,
    maxTP: 19,
    strength: "max",
    minNumS: 4,
    maxNumS: 4,
    minNumH: "",
    maxNumH: 3,
    minNumD: "",
    maxNumD: 3,
    minNumC: 6,
    maxNumC: 6,
    sLong: "c",
    o1bIndex: 1,
    o1Bid: "1c",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 13,
    maxTP: 15,
    strength: "min",
    minNumS: "",
    maxNumS: 3,
    minNumH: "",
    maxNumH: 3,
    minNumD: 6,
    maxNumD: 6,
    minNumC: 4,
    maxNumC: 4,
    sLong: "d",
    o1bIndex: 2,
    o1Bid: "1d",
  },
  {
    bidder: "o1",
    weight: 2,
    minTP: 16,
    maxTP: 17,
    strength: "med",
    minNumS: "",
    maxNumS: 3,
    minNumH: "",
    maxNumH: 3,
    minNumD: 6,
    maxNumD: 6,
    minNumC: 4,
    maxNumC: 4,
    sLong: "d",
    o1bIndex: 2,
    o1Bid: "1d",
  },
  {
    bidder: "o1",
    weight: 2,
    minTP: 18,
    maxTP: 19,
    strength: "max",
    minNumS: "",
    maxNumS: 3,
    minNumH: "",
    maxNumH: 3,
    minNumD: 6,
    maxNumD: 6,
    minNumC: 4,
    maxNumC: 4,
    sLong: "d",
    o1bIndex: 2,
    o1Bid: "1d",
  },
  {
    bidder: "o1",
    weight: 2,
    minTP: 13,
    maxTP: 15,
    strength: "min",
    minNumS: "",
    maxNumS: 3,
    minNumH: 4,
    maxNumH: 4,
    minNumD: 6,
    maxNumD: 6,
    minNumC: "",
    maxNumC: 3,
    sLong: "d",
    o1bIndex: 2,
    o1Bid: "1d",
  },
  {
    bidder: "o1",
    weight: 2,
    minTP: 16,
    maxTP: 17,
    strength: "med",
    minNumS: "",
    maxNumS: 3,
    minNumH: 4,
    maxNumH: 4,
    minNumD: 6,
    maxNumD: 6,
    minNumC: "",
    maxNumC: 3,
    sLong: "d",
    o1bIndex: 2,
    o1Bid: "1d",
  },
  {
    bidder: "o1",
    weight: 2,
    minTP: 18,
    maxTP: 19,
    strength: "max",
    minNumS: "",
    maxNumS: 3,
    minNumH: 4,
    maxNumH: 4,
    minNumD: 6,
    maxNumD: 6,
    minNumC: "",
    maxNumC: 3,
    sLong: "d",
    o1bIndex: 2,
    o1Bid: "1d",
  },
  {
    bidder: "o1",
    weight: 2,
    minTP: 13,
    maxTP: 15,
    strength: "min",
    minNumS: 4,
    maxNumS: 4,
    minNumH: "",
    maxNumH: "",
    minNumD: 6,
    maxNumD: 6,
    minNumC: "",
    maxNumC: 3,
    sLong: "d",
    o1bIndex: 2,
    o1Bid: "1d",
  },
  {
    bidder: "o1",
    weight: 2,
    minTP: 16,
    maxTP: 17,
    strength: "med",
    minNumS: 4,
    maxNumS: 4,
    minNumH: "",
    maxNumH: "",
    minNumD: 6,
    maxNumD: 6,
    minNumC: "",
    maxNumC: 3,
    sLong: "d",
    o1bIndex: 2,
    o1Bid: "1d",
  },
  {
    bidder: "o1",
    weight: 2,
    minTP: 18,
    maxTP: 19,
    strength: "max",
    minNumS: 4,
    maxNumS: 4,
    minNumH: "",
    maxNumH: "",
    minNumD: 6,
    maxNumD: 6,
    minNumC: "",
    maxNumC: 3,
    sLong: "d",
    o1bIndex: 2,
    o1Bid: "1d",
  },
  {
    bidder: "o1",
    weight: 2,
    minTP: 13,
    maxTP: 15,
    strength: "min",
    minNumS: "",
    maxNumS: 3,
    minNumH: 6,
    maxNumH: 6,
    minNumD: "",
    maxNumD: 3,
    minNumC: 4,
    maxNumC: 4,
    sLong: "h",
    o1bIndex: 3,
    o1Bid: "1h",
  },
  {
    bidder: "o1",
    weight: 2,
    minTP: 16,
    maxTP: 17,
    strength: "med",
    minNumS: "",
    maxNumS: 3,
    minNumH: 6,
    maxNumH: 6,
    minNumD: "",
    maxNumD: 3,
    minNumC: 4,
    maxNumC: 4,
    sLong: "h",
    o1bIndex: 3,
    o1Bid: "1h",
  },
  {
    bidder: "o1",
    weight: 2,
    minTP: 18,
    maxTP: 19,
    strength: "max",
    minNumS: "",
    maxNumS: 3,
    minNumH: 6,
    maxNumH: 6,
    minNumD: "",
    maxNumD: 3,
    minNumC: 4,
    maxNumC: 4,
    sLong: "h",
    o1bIndex: 3,
    o1Bid: "1h",
  },
  {
    bidder: "o1",
    weight: 2,
    minTP: 13,
    maxTP: 15,
    strength: "min",
    minNumS: "",
    maxNumS: 3,
    minNumH: 6,
    maxNumH: 6,
    minNumD: 4,
    maxNumD: 4,
    minNumC: "",
    maxNumC: 3,
    sLong: "h",
    o1bIndex: 3,
    o1Bid: "1h",
  },
  {
    bidder: "o1",
    weight: 2,
    minTP: 16,
    maxTP: 17,
    strength: "med",
    minNumS: "",
    maxNumS: 3,
    minNumH: 6,
    maxNumH: 6,
    minNumD: 4,
    maxNumD: 4,
    minNumC: "",
    maxNumC: 3,
    sLong: "h",
    o1bIndex: 3,
    o1Bid: "1h",
  },
  {
    bidder: "o1",
    weight: 1,
    minTP: 18,
    maxTP: 19,
    strength: "max",
    minNumS: "",
    maxNumS: 3,
    minNumH: 6,
    maxNumH: 6,
    minNumD: 4,
    maxNumD: 4,
    minNumC: "",
    maxNumC: 3,
    sLong: "h",
    o1bIndex: 3,
    o1Bid: "1h",
  },
  {
    bidder: "o1",
    weight: 2,
    minTP: 13,
    maxTP: 15,
    strength: "min",
    minNumS: 4,
    maxNumS: 4,
    minNumH: 6,
    maxNumH: 6,
    minNumD: 6,
    maxNumD: 3,
    minNumC: "",
    maxNumC: 3,
    sLong: "h",
    o1bIndex: 3,
    o1Bid: "1h",
  },
  {
    bidder: "o1",
    weight: 2,
    minTP: 16,
    maxTP: 17,
    strength: "med",
    minNumS: 4,
    maxNumS: 4,
    minNumH: 6,
    maxNumH: 6,
    minNumD: 6,
    maxNumD: 3,
    minNumC: "",
    maxNumC: 3,
    sLong: "h",
    o1bIndex: 3,
    o1Bid: "1h",
  },
  {
    bidder: "o1",
    weight: 2,
    minTP: 18,
    maxTP: 19,
    strength: "max",
    minNumS: 4,
    maxNumS: 4,
    minNumH: 6,
    maxNumH: 6,
    minNumD: 6,
    maxNumD: 3,
    minNumC: "",
    maxNumC: 3,
    sLong: "h",
    o1bIndex: 3,
    o1Bid: "1h",
  },
  {
    bidder: "o1",
    weight: 2,
    minTP: 13,
    maxTP: 15,
    strength: "min",
    minNumS: 6,
    maxNumS: 6,
    minNumH: "",
    maxNumH: 3,
    minNumD: "",
    maxNumD: 3,
    minNumC: 4,
    maxNumC: 4,
    sLong: "s",
    o1bIndex: 4,
    o1Bid: "1s",
  },
  {
    bidder: "o1",
    weight: 2,
    minTP: 16,
    maxTP: 17,
    strength: "med",
    minNumS: 6,
    maxNumS: 6,
    minNumH: "",
    maxNumH: 3,
    minNumD: "",
    maxNumD: 3,
    minNumC: 4,
    maxNumC: 4,
    sLong: "s",
    o1bIndex: 4,
    o1Bid: "1s",
  },
  {
    bidder: "o1",
    weight: 2,
    minTP: 18,
    maxTP: 19,
    strength: "max",
    minNumS: 6,
    maxNumS: 6,
    minNumH: "",
    maxNumH: 3,
    minNumD: "",
    maxNumD: 3,
    minNumC: 4,
    maxNumC: 4,
    sLong: "s",
    o1bIndex: 4,
    o1Bid: "1s",
  },
  {
    bidder: "o1",
    weight: 2,
    minTP: 13,
    maxTP: 15,
    strength: "min",
    minNumS: 6,
    maxNumS: 6,
    minNumH: "",
    maxNumH: 3,
    minNumD: 4,
    maxNumD: 4,
    minNumC: "",
    maxNumC: 3,
    sLong: "s",
    o1bIndex: 4,
    o1Bid: "1s",
  },
  {
    bidder: "o1",
    weight: 2,
    minTP: 16,
    maxTP: 17,
    strength: "med",
    minNumS: 6,
    maxNumS: 6,
    minNumH: "",
    maxNumH: 3,
    minNumD: 4,
    maxNumD: 4,
    minNumC: "",
    maxNumC: 3,
    sLong: "s",
    o1bIndex: 4,
    o1Bid: "1s",
  },
  {
    bidder: "o1",
    weight: 2,
    minTP: 18,
    maxTP: 19,
    strength: "max",
    minNumS: 6,
    maxNumS: 6,
    minNumH: "",
    maxNumH: 3,
    minNumD: 4,
    maxNumD: 4,
    minNumC: "",
    maxNumC: 3,
    sLong: "s",
    o1bIndex: 4,
    o1Bid: "1s",
  },
  {
    bidder: "o1",
    weight: 2,
    minTP: 13,
    maxTP: 15,
    strength: "min",
    minNumS: 6,
    maxNumS: 6,
    minNumH: 4,
    maxNumH: 4,
    minNumD: "",
    maxNumD: 3,
    minNumC: "",
    maxNumC: 3,
    sLong: "s",
    o1bIndex: 4,
    o1Bid: "1s",
  },
  {
    bidder: "o1",
    weight: 2,
    minTP: 16,
    maxTP: 17,
    strength: "med",
    minNumS: 6,
    maxNumS: 6,
    minNumH: 4,
    maxNumH: 4,
    minNumD: "",
    maxNumD: 3,
    minNumC: "",
    maxNumC: 3,
    sLong: "s",
    o1bIndex: 4,
    o1Bid: "1s",
  },
  {
    bidder: "o1",
    weight: 2,
    minTP: 18,
    maxTP: 19,
    strength: "max",
    minNumS: 6,
    maxNumS: 6,
    minNumH: 4,
    maxNumH: 4,
    minNumD: "",
    maxNumD: 3,
    minNumC: "",
    maxNumC: 3,
    sLong: "s",
    o1bIndex: 4,
    o1Bid: "1s",
  },
];
var rebidSixCardFourCard = sixCardFourCard.filter(
  (itemsInArray) =>
    hand.strength === itemsInArray.strength &&
    (hand.numS >= itemsInArray.minNumS || itemsInArray.minNumS === "") &&
    (hand.numS <= itemsInArray.maxNumS || itemsInArray.maxNumS === "") &&
    (hand.numH >= itemsInArray.minNumH || itemsInArray.minNumH === "") &&
    (hand.numH <= itemsInArray.maxNumH || itemsInArray.maxNumH === "") &&
    (hand.numD >= itemsInArray.minNumD || itemsInArray.minNumD === "") &&
    (hand.numD <= itemsInArray.maxNumD || itemsInArray.maxNumD === "") &&
    (hand.numC >= itemsInArray.minNumC || itemsInArray.minNumC === "") &&
    (hand.numC <= itemsInArray.maxNumC || itemsInArray.maxNumC === "")
);
