function getaocp1_respondTo1NT(hand) {
  var aocp1_respondTo1NT = [
    {
      bidder: "ocp1",
      minHCP: 11,
      maxHCP: 12,
      strength: "art",
      oc1Index: 5,
      oc1Bid: "1nt",
      minNumS: 4,
      maxNumS: "",
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      ocp1Index: 6,
      ocp1Bid: "2c",
    },
    {
      bidder: "ocp1",
      minHCP: 13,
      maxHCP: 19,
      strength: "art",
      oc1Index: 5,
      oc1Bid: "1nt",
      minNumS: 4,
      maxNumS: "",
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      ocp1Index: 6,
      ocp1Bid: "2c",
    },
    {
      bidder: "ocp1",
      minHCP: 11,
      maxHCP: 12,
      strength: "art",
      oc1Index: 5,
      oc1Bid: "1nt",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: "",
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      ocp1Index: 6,
      ocp1Bid: "2c",
    },
    {
      bidder: "ocp1",
      minHCP: 13,
      maxHCP: 19,
      strength: "art",
      oc1Index: 5,
      oc1Bid: "1nt",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: "",
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      ocp1Index: 6,
      ocp1Bid: "2c",
    },
    {
      bidder: "ocp1",
      minHCP: 11,
      maxHCP: 12,
      strength: "art",
      oc1Index: 5,
      oc1Bid: "1nt",
      minNumS: 4,
      maxNumS: "",
      minNumH: 4,
      maxNumH: "",
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      ocp1Index: 6,
      ocp1Bid: "2c",
    },
    {
      bidder: "ocp1",
      minHCP: 13,
      maxHCP: 19,
      strength: "art",
      oc1Index: 5,
      oc1Bid: "1nt",
      minNumS: 4,
      maxNumS: "",
      minNumH: 4,
      maxNumH: "",
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      ocp1Index: 6,
      ocp1Bid: "2c",
    },
    {
      bidder: "ocp1",
      minHCP: 9,
      maxHCP: 10,
      strength: "art",
      oc1Index: 5,
      oc1Bid: "1nt",
      minNumS: 4,
      maxNumS: "",
      minNumH: 5,
      maxNumH: "",
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      ocp1Index: 6,
      ocp1Bid: "2c",
    },
    {
      bidder: "ocp1",
      minHCP: 9,
      maxHCP: 10,
      strength: "art",
      oc1Index: 5,
      oc1Bid: "1nt",
      minNumS: 5,
      maxNumS: "",
      minNumH: 4,
      maxNumH: "",
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      ocp1Index: 6,
      ocp1Bid: "2c",
    },
    {
      bidder: "ocp1",
      minHCP: 9,
      maxHCP: 10,
      strength: "art",
      oc1Index: 5,
      oc1Bid: "1nt",
      minNumS: 4,
      maxNumS: "",
      minNumH: 4,
      maxNumH: "",
      minNumD: 4,
      maxNumD: "",
      minNumC: "",
      maxNumC: 3,
      ocp1Index: 6,
      ocp1Bid: "2c",
    },
    {
      bidder: "ocp1",
      minHCP: 9,
      maxHCP: 10,
      strength: "art",
      oc1Index: 5,
      oc1Bid: "1nt",
      minNumS: 4,
      maxNumS: "",
      minNumH: 4,
      maxNumH: "",
      minNumD: "",
      maxNumD: 3,
      minNumC: 6,
      maxNumC: "",
      ocp1Index: 6,
      ocp1Bid: "2c",
    },
    {
      bidder: "ocp1",
      minHCP: 0,
      maxHCP: 10,
      strength: "min",
      oc1Index: 5,
      oc1Bid: "1nt",
      minNumS: "",
      maxNumS: 4,
      minNumH: "",
      maxNumH: 4,
      minNumD: 5,
      maxNumD: "",
      minNumC: "",
      maxNumC: 3,
      ocp1Index: 7,
      ocp1Bid: "2d",
    },
    {
      bidder: "ocp1",
      minHCP: 0,
      maxHCP: 10,
      strength: "min",
      oc1Index: 5,
      oc1Bid: "1nt",
      minNumS: "",
      maxNumS: 5,
      minNumH: 5,
      maxNumH: "",
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      ocp1Index: 8,
      ocp1Bid: "2h",
    },
    {
      bidder: "ocp1",
      minHCP: 0,
      maxHCP: 10,
      strength: "min",
      oc1Index: 5,
      oc1Bid: "1nt",
      minNumS: 5,
      maxNumS: "",
      minNumH: "",
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      ocp1Index: 9,
      ocp1Bid: "2s",
    },
    {
      bidder: "ocp1",
      minHCP: 10,
      maxHCP: 10,
      strength: "min",
      oc1Index: 5,
      oc1Bid: "1nt",
      minNumS: 4,
      maxNumS: 4,
      minNumH: 3,
      maxNumH: 3,
      minNumD: 3,
      maxNumD: 3,
      minNumC: 3,
      maxNumC: 3,
      ocp1Index: 8,
      ocp1Bid: "2s",
    },
    {
      bidder: "ocp1",
      minHCP: 10,
      maxHCP: 10,
      strength: "min",
      oc1Index: 5,
      oc1Bid: "1nt",
      minNumS: 3,
      maxNumS: 3,
      minNumH: 4,
      maxNumH: 4,
      minNumD: 3,
      maxNumD: 3,
      minNumC: 3,
      maxNumC: 3,
      ocp1Index: 7,
      ocp1Bid: "2h",
    },
    {
      bidder: "ocp1",
      minHCP: 10,
      maxHCP: 10,
      strength: "min",
      oc1Index: 5,
      oc1Bid: "1nt",
      minNumS: 3,
      maxNumS: 3,
      minNumH: 3,
      maxNumH: 3,
      minNumD: 4,
      maxNumD: 4,
      minNumC: 3,
      maxNumC: 3,
      ocp1Index: 6,
      ocp1Bid: "2d",
    },
    {
      bidder: "ocp1",
      minHCP: 10,
      maxHCP: 10,
      strength: "min",
      oc1Index: 5,
      oc1Bid: "1nt",
      minNumS: 3,
      maxNumS: 3,
      minNumH: 3,
      maxNumH: 3,
      minNumD: 3,
      maxNumD: 3,
      minNumC: 3,
      maxNumC: 4,
      ocp1Index: 4,
      ocp1Bid: "2c",
    },
    {
      bidder: "ocp1",
      minHCP: 11,
      maxHCP: 12,
      strength: "med",
      oc1Index: 5,
      oc1Bid: "1nt",
      minNumS: 2,
      maxNumS: 4,
      minNumH: 2,
      maxNumH: 4,
      minNumD: 2,
      maxNumD: 4,
      minNumC: 2,
      maxNumC: 4,
      ocp1Index: 10,
      ocp1Bid: "2nt",
    },
    {
      bidder: "ocp1",
      minHCP: 13,
      maxHCP: 19,
      strength: "med",
      oc1Index: 5,
      oc1Bid: "1nt",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: 5,
      maxNumC: "",
      ocp1Index: 11,
      ocp1Bid: "3c",
    },
    {
      bidder: "ocp1",
      minHCP: 13,
      maxHCP: 19,
      strength: "med",
      oc1Index: 5,
      oc1Bid: "1nt",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 5,
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      ocp1Index: 12,
      ocp1Bid: "3d",
    },
    {
      bidder: "ocp1",
      minHCP: 13,
      maxHCP: 19,
      strength: "med",
      oc1Index: 5,
      oc1Bid: "1nt",
      minNumS: "",
      maxNumS: 3,
      minNumH: 5,
      maxNumH: "",
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      ocp1Index: 13,
      ocp1Bid: "3h",
    },
    {
      bidder: "ocp1",
      minHCP: 13,
      maxHCP: 19,
      strength: "med",
      oc1Index: 5,
      oc1Bid: "1nt",
      minNumS: 5,
      maxNumS: "",
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      ocp1Index: 14,
      ocp1Bid: "3s",
    },
    {
      bidder: "ocp1",
      minHCP: 13,
      maxHCP: 16,
      strength: "max",
      oc1Index: 5,
      oc1Bid: "1nt",
      minNumS: 2,
      maxNumS: 4,
      minNumH: 2,
      maxNumH: 4,
      minNumD: 2,
      maxNumD: 4,
      minNumC: 2,
      maxNumC: 4,
      ocp1Index: 10,
      ocp1Bid: "3nt",
    },
    {
      bidder: "ocp1",
      minHCP: 24,
      maxHCP: 32,
      strength: "slam",
      oc1Index: 5,
      oc1Bid: "1nt",
      minNumS: 2,
      maxNumS: 4,
      minNumH: 2,
      maxNumH: 4,
      minNumD: 2,
      maxNumD: 4,
      minNumC: 2,
      maxNumC: 4,
      ocp1Index: 15,
      ocp1Bid: "4nt",
    },
    {
      bidder: "ocp1",
      minHCP: 3,
      maxHCP: 6,
      strength: "art",
      oc1Index: 10,
      oc1Bid: "2nt",
      minNumS: 4,
      maxNumS: "",
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      ocp1Index: 11,
      ocp1Bid: "3c",
    },
    {
      bidder: "ocp1",
      minHCP: 3,
      maxHCP: 6,
      strength: "art",
      oc1Index: 10,
      oc1Bid: "2nt",
      minNumS: 4,
      maxNumS: "",
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      ocp1Index: 11,
      ocp1Bid: "3c",
    },
    {
      bidder: "ocp1",
      minHCP: 3,
      maxHCP: 6,
      strength: "art",
      oc1Index: 10,
      oc1Bid: "2nt",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: "",
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      ocp1Index: 11,
      ocp1Bid: "3c",
    },
    {
      bidder: "ocp1",
      minHCP: 3,
      maxHCP: 6,
      strength: "art",
      oc1Index: 10,
      oc1Bid: "2nt",
      minNumS: "",
      maxNumS: 3,
      minNumH: 4,
      maxNumH: "",
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      ocp1Index: 11,
      ocp1Bid: "3c",
    },
    {
      bidder: "ocp1",
      minHCP: 3,
      maxHCP: 6,
      strength: "art",
      oc1Index: 10,
      oc1Bid: "2nt",
      minNumS: 4,
      maxNumS: "",
      minNumH: 4,
      maxNumH: "",
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      ocp1Index: 11,
      ocp1Bid: "3c",
    },
    {
      bidder: "ocp1",
      minHCP: 3,
      maxHCP: 6,
      strength: "art",
      oc1Index: 10,
      oc1Bid: "2nt",
      minNumS: 4,
      maxNumS: "",
      minNumH: 4,
      maxNumH: "",
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      ocp1Index: 11,
      ocp1Bid: "3c",
    },
    {
      bidder: "ocp1",
      minHCP: 3,
      maxHCP: 6,
      strength: "min",
      oc1Index: 10,
      oc1Bid: "2nt",
      minNumS: "",
      maxNumS: 4,
      minNumH: "",
      maxNumH: 4,
      minNumD: 5,
      maxNumD: "",
      minNumC: "",
      maxNumC: 3,
      ocp1Index: 7,
      ocp1Bid: "3d",
    },
    {
      bidder: "ocp1",
      minHCP: 3,
      maxHCP: 6,
      strength: "min",
      oc1Index: 10,
      oc1Bid: "2nt",
      minNumS: "",
      maxNumS: 5,
      minNumH: 5,
      maxNumH: "",
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      ocp1Index: 8,
      ocp1Bid: "3h",
    },
    {
      bidder: "ocp1",
      minHCP: 3,
      maxHCP: 6,
      strength: "min",
      oc1Index: 10,
      oc1Bid: "2nt",
      minNumS: 5,
      maxNumS: "",
      minNumH: "",
      maxNumH: 4,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      ocp1Index: 9,
      ocp1Bid: "3s",
    },
    {
      bidder: "ocp1",
      minHCP: 3,
      maxHCP: 5,
      strength: "min",
      oc1Index: 10,
      oc1Bid: "2nt",
      minNumS: 2,
      maxNumS: 4,
      minNumH: 2,
      maxNumH: 4,
      minNumD: 2,
      maxNumD: 4,
      minNumC: 2,
      maxNumC: 4,
      ocp1Index: 10,
      ocp1Bid: "3nt",
    },
    {
      bidder: "ocp1",
      minHCP: 0,
      maxHCP: 2,
      strength: "min",
      oc1Index: 10,
      oc1Bid: "2nt",
      minNumS: "",
      maxNumS: 3,
      minNumH: "",
      maxNumH: 3,
      minNumD: 5,
      maxNumD: "",
      minNumC: "",
      maxNumC: 3,
      ocp1Index: 12,
      ocp1Bid: "3d",
    },
    {
      bidder: "ocp1",
      minHCP: 0,
      maxHCP: 2,
      strength: "min",
      oc1Index: 10,
      oc1Bid: "2nt",
      minNumS: "",
      maxNumS: 3,
      minNumH: 5,
      maxNumH: "",
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      ocp1Index: 13,
      ocp1Bid: "3h",
    },
    {
      bidder: "ocp1",
      minHCP: 0,
      maxHCP: 2,
      strength: "min",
      oc1Index: 10,
      oc1Bid: "2nt",
      minNumS: 5,
      maxNumS: "",
      minNumH: "",
      maxNumH: 3,
      minNumD: "",
      maxNumD: 3,
      minNumC: "",
      maxNumC: 3,
      ocp1Index: 14,
      ocp1Bid: "3s",
    },
    {
      bidder: "ocp1",
      minHCP: 16,
      maxHCP: 22,
      strength: "max",
      oc1Index: 10,
      oc1Bid: "2nt",
      minNumS: 2,
      maxNumS: 4,
      minNumH: 2,
      maxNumH: 4,
      minNumD: 2,
      maxNumD: 4,
      minNumC: 2,
      maxNumC: 4,
      ocp1Index: 15,
      ocp1Bid: "4nt",
    },
  ];

  var rebidAocp1_respondTo1NT = aocp1_respondTo1NT.filter(
    (itemsInArray) =>
      hand.ocpStrength === itemsInArray.strength &&
      (hand.numS >= itemsInArray.minNumS || itemsInArray.minNumS === "") &&
      (hand.numS <= itemsInArray.maxNumS || itemsInArray.maxNumS === "") &&
      (hand.numH >= itemsInArray.minNumH || itemsInArray.minNumH === "") &&
      (hand.numH <= itemsInArray.maxNumH || itemsInArray.maxNumH === "") &&
      (hand.numD >= itemsInArray.minNumD || itemsInArray.minNumD === "") &&
      (hand.numD <= itemsInArray.maxNumD || itemsInArray.maxNumD === "") &&
      (hand.numC >= itemsInArray.minNumC || itemsInArray.minNumC === "") &&
      (hand.numC <= itemsInArray.maxNumC || itemsInArray.maxNumC === "")
  );
  return rebidAocp1_respondTo1NT;
}
