function getaocp1_7to10(hand) {
  var aocp1_7to10 = [
    {
      bidder: "ocp1",
      oc1Index: 2,
      oc1Bid: "1d",
      minHCP: 7,
      maxHCP: 10,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 3,
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      ocp1Index: 7,
      ocp1Bid: "2d",
    },
    {
      bidder: "ocp1",
      oc1Index: 3,
      oc1Bid: "1h",
      minHCP: 7,
      maxHCP: 10,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 3,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      ocp1Index: 8,
      ocp1Bid: "2h",
    },
    {
      bidder: "ocp1",
      oc1Index: 4,
      oc1Bid: "1s",
      minHCP: 7,
      maxHCP: 10,
      strength: "min",
      minNumS: 3,
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      ocp1Index: 9,
      ocp1Bid: "2s",
    },
    {
      bidder: "ocp1",
      oc1Index: 6,
      oc1Bid: "2c",
      minHCP: 7,
      maxHCP: 10,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 3,
      maxNumC: "",
      ocp1Index: 11,
      ocp1Bid: "3c",
    },
    {
      bidder: "ocp1",
      oc1Index: 7,
      oc1Bid: "2d",
      minHCP: 7,
      maxHCP: 10,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 3,
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      ocp1Index: 12,
      ocp1Bid: "3d",
    },
    {
      bidder: "ocp1",
      oc1Index: 8,
      oc1Bid: "2h",
      minHCP: 7,
      maxHCP: 10,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 3,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      ocp1Index: 13,
      ocp1Bid: "3h",
    },
    {
      bidder: "ocp1",
      oc1Index: 9,
      oc1Bid: "2s",
      minHCP: 7,
      maxHCP: 10,
      strength: "min",
      minNumS: 3,
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      ocp1Index: 14,
      ocp1Bid: "3s",
    },
    {
      bidder: "ocp1",
      oc1Index: 11,
      oc1Bid: "3c",
      minHCP: 7,
      maxHCP: 10,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: 3,
      maxNumC: "",
      ocp1Index: 16,
      ocp1Bid: "4c",
    },
    {
      bidder: "ocp1",
      oc1Index: 12,
      oc1Bid: "3d",
      minHCP: 7,
      maxHCP: 10,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: 3,
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      ocp1Index: 17,
      ocp1Bid: "4d",
    },
    {
      bidder: "ocp1",
      oc1Index: 13,
      oc1Bid: "3h",
      minHCP: 7,
      maxHCP: 10,
      strength: "min",
      minNumS: "",
      maxNumS: "",
      minNumH: 3,
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      ocp1Index: 18,
      ocp1Bid: "4h",
    },
    {
      bidder: "ocp1",
      oc1Index: 14,
      oc1Bid: "3s",
      minHCP: 7,
      maxHCP: 10,
      strength: "min",
      minNumS: 3,
      maxNumS: "",
      minNumH: "",
      maxNumH: "",
      minNumD: "",
      maxNumD: "",
      minNumC: "",
      maxNumC: "",
      ocp1Index: 19,
      ocp1Bid: "4s",
    },
  ];

  var rebidAocp1_7to10 = aocp1_7to10.filter(
    (itemsInArray) =>
      hand.ocpStrength === itemsInArray.strength &&
      (hand.numS >= itemsInArray.minNumS || itemsInArray.minNumS === "") &&
      (hand.numS <= itemsInArray.maxNumS || itemsInArray.maxNumS === "") &&
      (hand.numH >= itemsInArray.minNumH || itemsInArray.minNumH === "") &&
      (hand.numH <= itemsInArray.maxNumH || itemsInArray.maxNumH === "") &&
      (hand.numD >= itemsInArray.minNumD || itemsInArray.minNumD === "") &&
      (hand.numD <= itemsInArray.maxNumD || itemsInArray.maxNumD === "") &&
      (hand.numC >= itemsInArray.minNumC || itemsInArray.minNumC === "") &&
      (hand.numC <= itemsInArray.maxNumC || itemsInArray.maxNumC === "")
  );
  return rebidAocp1_7to10;
}
